#!/bin/bash

IDX=
PHRASE=

function print_help
{
    echo "Usage:"
    echo "	hgrep IDX PHRASE"
    echo "	hgrep DIST PHRASE"
    echo "	hgrep DIST PKG... PHRASE"
    echo ""
    echo "Example: "
    echo "	hgrep /srv/sources/dists/rhel5su4/packages/k/kernel/plugins/hyperestraier/idx \"Ingo\""
    echo "	hgrep rhel5su4 \"Ingo\""
    echo "	hgrep rhel5su4 kernel \"Ingo\""
    echo "      hgrep rhel5su4 kernel glibc \"waitpid\""
    echo ""

    exit $1
}

function parse_arguments
{
    if   [ "$#" = 1 ]; then
	if [ $1 = "--help" ] || [ $1 = "-h" ] ; then
	    print_help 0 1>&2
	else
	    print_help 1 1>&2
	fi
    elif [ "$#" = 2 ]; then
	IDX="$1"
	if ! [ -d $IDX ]; then
	    IDX=/srv/sources/dists/$IDX/plugin/hyperestraier/idx
	    if ! [ -d $IDX ]; then
		echo "No such directory: $IDX" 1>&2
		exit 1
	    fi
	fi
	PHRASE="$2"
    elif [ "$#" -ge 3 ]; then
	local dist=$1
	shift 1

	while [ $# -gt 1 ]; do
	    IDX="$IDX /srv/sources/dists/$dist/packages/${1:0:1}/$1/plugins/hyperestraier/idx"
	    shift 1
	done
	PHRASE="$1"
	shift 1
    else
	print_help 1 1>&2
    fi
}

function main
{
    local r=1
    local r0


    parse_arguments "$@"

    if ! [ -d "/srv/sources" ]; then
	echo "Cannot find /srv/sources" 1>&2
	return 1
    fi

    for i in $IDX; do
	estcmd search -max 10000 -vu "$i" "$PHRASE" 2>&1 \
	    | grep -e 'file:///' | sed -e 's#[0-9]\+	file://##' \
	    | xargs -n 1 grep -nH -e "$PHRASE"
	r0=$?

	if [ $r != 0 ]; then
	    r=$r0
	fi
    done

    return $r
}

main "$@"

# estcmd search -vu /srv/sources/dists/rhel5su4/packages/k/kernel/plugins/hyperestraier/idx "Ingo"
# xargs -0 -e grep -nH -e 