#!/bin/bash

source liblcopy.sh &&  exit 1

CONF_BRANCH=
CONF_PACKAGE=


function print_usage
{
    echo "Usage: "
    echo "$0 --help|-h"
    echo "$0 PACKAGE:BRANCH VCS-COMMANDS..."
    echo ""

    echo "VCS-COMMANDS format:"
    lcopy_backends_help checkout
}

function main
{
    local package_branch
    local vcs
    local conf
    local status


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    ;;
	    --*)
		echo "unknown option: $1" 1>&2
		print_usage 1>&2
		exit 1
		;;
	    *)
		package_branch=$1
		shift
		break
		;;
	esac
	shift
    done

    if [ -z "$package_branch" ]; then
	echo "given no package:branch: $@" 1>&2
	print_usage 1>&2
	exit 1
    fi
    
    if ! [[ "${package_branch}" =~ "([-a-zA-Z0-9]+)(:([-a-zA-Z0-9]+))?" ]]; then
	echo "broken package:branch specification: ${package:branch}" 1>&2
	print_usage 1>&2
	exit 1
    else
	CONF_PACKAGE=${BASH_REMATCH[1]}
	CONF_BRANCH=${BASH_REMATCH[2]}
    fi
    
    if [ $# -eq 0 ]; then
	echo "given no vcs command: $@" 1>&2
	print_usage 1>&2
	exit 1
    fi

    vcs=$1
    shift

    conf=$(lcopy_backend_genconf $vcs "$@")
    status=$?

    if [ $status = 0 ]; then
	printf "(lcopy-checkout :package \"%s\" :branch \"%s\" :command %s)\n" \
	    "$CONF_PACKAGE" "$CONF_BRANCH" "$conf"
	return 0
    else
	return $status
    fi
}

main "$@"
