#!/bin/sh


rm -rf `pwd`/${TESTDIR}
make DESTDIR=`pwd`/${TESTDIR} -C ${top_builddir} install

PATH=`pwd`/${TESTDIR}/${bindir}:$PATH

source libsrpmix.sh || exit 1

{
    cat ${SRPMIX_BUILD_OPT_RULES_DIR}/*.scm \
    | test "x$(${GOSH} ${SRPMIX_HELPER_DIR}/build-opt-rules kernel-2.4.18-e.5)" = "x--target=ia64" 
} || exit 1 



{
    cat ${SRPMIX_BUILD_OPT_RULES_DIR}/*.scm \
    | test "x$(${GOSH} ${SRPMIX_HELPER_DIR}/build-opt-rules kernel-2.4.19-10)" = "x" 
} || exit 1 

exit 0
