#!/bin/bash

#
# Derived from eclass of gentoo.
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
function NOTIFY
{
    echo "Unknown command" $@
}

export command_not_found_handle=NOTIFY

declare -A L_SUPPORTED_VCS=(
    [cvs]=cvs
    [subversion]=svn
    [bzr]=bzr
    [darcs]=darcs
    [mercurial]=hg
    [git]=git
    [git-2]=git
)
L_VCS=

function print_usage
{
    echo "Usage: "
    echo "	$0 EBUILD-FILE"
}

function run_in_sandbox
{
    local cmd=$1
    local ebuild_file=$2
    local s

    local ltmpdir=`mktemp -d`
    trap "/bin/rm -rf $ltmpdir" 0
    if [ $? != 0 ]; then
	exit 2
    fi

    cp $ebuild_file $ltmpdir/ebuild
    if [ -f $cmd ]; then
	cp -ar $cmd $ltmpdir/cmd
    else
	cp -ar $(which $cmd) $ltmpdir/cmd
    fi

    cd $ltmpdir
    
    export PATH=
    /bin/bash -r $cmd
    return $s
}

function inherit
{
    local tmp

    for tmp in $@; do
	if [ -n "${L_SUPPORTED_VCS[${tmp}]}" ]; then
	    L_VCS=$tmp
	    break
	fi
    done
}
    
L_CVS_VARS="
    SERVER 
    MODULE
    USER
    PASS
    AUTH
    BRANCH
"
L_SVN_VARS="
    REPO_URI
    USER
    PASSWORD
"

L_BZR_VARS="
    REPO_URI
    BRANCH
"

L_DARCS_VARS="
    REPOSITORY
"

L_HG_VARS="
    REPO_URI
"

L_GIT_VARS="
    REPO_URI
    HAS_SUBMODULES
    MASTER
    BRANCH
"

function l-report
{
    local vcs=${L_SUPPORTED_VCS["$1"]}
    local p=E${vcs^^*}
    local a=L_${vcs^^*}_VARS
    local v

    if [ -z "$vcs" ]; then
	return 1
    fi
    

    echo LVCS=$vcs
    for v in ${!a}; do
	eval "printf \"${p}_${v}=%q\\n\" \$${p}_$v"
    done
    
    return 0
}

function main
{
    if [ -n "$PATH" ]; then
	
	while [ $# -gt 0 ]; do
	    case "$1" in
		*)
		    break
		    ;;
	    esac
	    shift
	done

	if [ $# != 1 ]; then
	    echo "too few argument" 1>&2
	    print_usage 1>&2
	    exit 2
	fi
	
	run_in_sandbox $0 $1
	exit $?
    else
	export PV=1
	source ebuild
	if [ -n "$PLEVEL" ]; then
	    return 1
	fi

	export PV=9999
	source ebuild

	export PV=99999999
	source ebuild
	
	
	if [ -z "$L_VCS" ]; then
	    return 1
	fi

	l-report $L_VCS
	exit $?
    fi
}

main "$@"
