#!/bin/sh
DIST=dist-f12-maven
KOJIURL=http://kojipkgs.fedoraproject.org
DIR=${1:-/srv/sources/attic/mirror/fedoraproject-koji}
PEEK=/dev/null

# TODO: Check gauche, wget, koji
function print_usage
{
    echo "Usage: "
    echo "	koji-mirror [DIR]"
}

function newer_name
{
    gosh -b -e "(begin (use gauche.version) (exit (if (version>? \"$1\" \"$2\" ) 0 1)))"
}

if ! test -d ${DIR}; then
    echo "No such directory: ${DIR}" 2>&1
    exit 1
fi

if test -f "${PEEK}" && test ${PEEK} != /dev/null; then
    cat "${PEEK}"
else
    koji latest-pkg --all --paths ${DIST} | tee ${PEEK} 
fi  | grep -v "^Build"						\
    | grep -v -e "^---"						\
    | cut -f 1 -d ' '						\
    | sed -e 's|/mnt/koji/packages/||'				\
    | tr / ' '							\
    | while read p v r; do
    c=${p:0:1}
    mkdir -p $DIR/$c
    (
	cd $DIR/$c; 
	f=$(ls $p-[0-9]*.src.rpm 2>/dev/null)
	if ! test -f "$f"; then
	    echo "(lcopy-koji new \"$p-$v-$r.src.rpm\")"
	    wget -q ${KOJIURL}/packages/$p/$v/$r/src/$p-$v-$r.src.rpm
	elif newer_name $v-$r.src.rpm $(echo "$f" | sed -e s"/$p-\(.*\)/\1/"); then
	    echo "(lcopy-koji update :new \"$p-$v-$r.src.rpm\" :old \"$f\")"
	    wget -q ${KOJIURL}/packages/$p/$v/$r/src/$p-$v-$r.src.rpm
	    rm "$f"
        else
	    echo "(lcopy-koji latest \"$p-$v-$r.src.rpm\" :date)"
	fi
	)
done
