#!/bin/sh
#
########################################################################
#
# lcopy-ctags: Run ctags as a plugin for lcopy-refresh
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

VCS="$1"
DIR="$2"
TSTAMP="$3"
OFILE=.__tags_lcopy__

CTAGS=ctags
BLACKLIST='.*\.bib$\|unic-005\.tex$\|.*\.srpmix$'



if test "$VCS" = mtn; then
    return 0;
fi

cd $DIR && find * -type f \! -regex ".*/\..*" \
	| egrep -v '/[^/]+\.[^/]+\.[^/]+$' \
        | egrep -v '/\.'         \
	| grep -v .bz2           \
	| grep -v .gz            \
	| grep -v "${BLACKLIST}" \
        | ${CTAGS} -f ${OFILE} -L -
