#!/usr/bin/env bash
#
# set -x
# 
########################################################################
#
# lcopy-rebirth: regenerate command lines to retrieve local copies
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Supported backends
VC="hg cvs svn git darcs bzr"

LIBLCOPY=liblcopy.sh

function generate_rebirth_cmdline
{
    (cd $1;
	for v in $VC; do
	    if ${v}_p; then
		${v}_rebirth
		return $?
	    fi
	done

	report_unsupported_vc $1

	return -1
	)
}

function report_unsupported_vc
{
    echo "# [-1] $1"
    echo "echo version control system used in $1 is not supported"
}

function report_no_vc
{
	echo "# [-2] $1"
        echo "echo $1 may not be under any version control system"
}

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	pwd 1>&2
	exit 1
    fi
}

try_source ${LIBLCOPY}

for d in "$@"; do
    if test -d "${d}"; then
    	generate_rebirth_cmdline "${d}"
    fi
done

# ;; just return, anoncvs, anonymous???
# /1 :pserver:anonymous@cvs.freetype.org:2401/cvs/freetype Ay=0=a%0bZ
# /1 :pserver:anonymous@cvs-mirror.mozilla.org:2401/cvsroot Ay=0=a%0bZ
# /1 :pserver:anonymous@cvs.freetype.org:2401/cvsroot Ay=0=a%0bZ
# /1 :pserver:anonymous@remotesensing.org:2401/cvs Ay=0=a%0bZ
# /1 :pserver:anonymous@cvs.imagemagick.org:2401/pathos/cvs Ay=0=a%0bZ

# /1 :pserver:anoncvs@anoncvs.netbsd.org:2401/cvsroot Ay=0=h<Z
# /1 :pserver:anoncvs@sources.redhat.com:2401/cvs/glibc Ay=0=h<Z
# /1 :pserver:anoncvs@oss.software.ibm.com:2401/usr/cvs/icu Ay=0=h<Z

# /1 :pserver:guest@openlab.ring.gr.jp:2401/circus/cvsroot AIbdZ,
# /1 :pserver:gnus@cvs.gnus.org:2401/usr/local/cvsroot AI=bZ

# /1 :pserver:anoncvs@sources.redhat.com:2401/cvs/src A

# vc-rebirth ends here
