#!/usr/bin/env bash
#
# set -x
#
########################################################################
#
# lcopy-refresh: sync local copy to repository of any version control system
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
LIBLCOPY=liblcopy.sh

# Supported backends
VC="cvs git svn arch hg darcs bzr mtn mtn_lcopy"
# TODO: svk?

DIR=`pwd`
LOG=/dev/stdout

PRIVATE_DIR=.lcopy

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}

function print_usage
{
    echo "Usage: "
    echo "lcopy-refresh [--log=logfile|-l=logfile|--log logfile|-l logfile]"
    echo "              [TOP_DIRECTORY]"
    echo "lcopy-refresh --list-plugins|-L"
    echo "lcopy-refresh --help"
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}


function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    --log|-l)
		if [ $# -gt 0 ]; then
		    shift 1

		    LOG=$1
		    shift 1
		else
		    echo no option argument for "$1" 1>&1
		    print_usage 1>&2
		    abort
		fi
		;;
	    --log=*)
		LOG=`echo $1 | sed -e 's/--log=//'`
		shift 1
		;;
	    -l=*)
		LOG=`echo $1 | sed -e 's/--l=//'`
		shift 1
		;;
	    --list-plugins|-L)
	        lcopy_list_plugins
	        exit 0
	        ;;
	    -*)
		echo unknown option: "$1" 1>&2
		print_usage 1>&2
		abort
		;;
	    *)
		break
		;;
	esac
    done

    if test $# -gt 1; then
	echo "too many arguments" 1>&2
	print_usage 1>&2
	abort
    elif test $# = 1; then
	DIR=$1
	shift
    fi

    if test ! -w $LOG; then
	if test x"$LOG" = x/dev/null; then
	    LOG=/dev/null
	fi 
    fi
}

function refresh
{
    r=
    tstamp=
    cur_dir=

    cd $1

    for v in $VC; do
	if ${v}_p; then

	    cur_dir=`pwd`
	    tstamp=`LANG=C date`
	    es_print lcopy start-updating    \
		--vcs=${v}                   \
		--directory=\"${cur_dir}\"   \
		--date=\"${tstamp}\"  >> $LOG

	    ${v}_update $LOG
	    r=$?

	    mkdir -p "${PRIVATE_DIR}"
	    echo $r > "${PRIVATE_DIR}"/STATUS

	    tstamp=`LANG=C date`
	    if test $r = 0; then
		es_print lcopy successful-in-updating --directory=\"${cur_dir}\"  --date=\"${tstamp}\" --status=$r
	    else
		es_print lcopy fail-in-updating --directory=\"${cur_dir}\"  --date=\"${tstamp}\" --status=$r
	    fi  >> $LOG

	    if test $r = 0; then
		lcopy_run_plugins "$LOG" "${v}" "${cur_dir}" "${tstamp}"
	    fi

	    return $r
	fi
    done


    for d in *; do
	if test -d "${d}"; then
	   (refresh "${d}")
	fi
    done
}



function main
{
    parse_arguments "$@"
    refresh ${DIR}
}

LANG=C

try_source ${LIBLCOPY}
main "$@"

# lcopy-refresh ends here
