#!/bin/sh
#
########################################################################
#
# srpmix-ctags: Run ctags for files under srpmix dir
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# TODO: Untidy ctags and etags code.

ROOTDIR=
CTAGS=ctags

BUILDDIR=
CTAGSDIR=
LOGDIR=
LOGFILE=
LIBSRPMIX=libsrpmix.sh

BLACKLIST='.*\.srpmix$'

function print_usage
{
    echo "Usage: "
    echo "  srpmix-ctags [--help|-h]"
    echo "  srpmix-ctags ROOTDIR"
    echo 
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}

function parse_arguments
{
    status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    BUILDDIR=${ROOTDIR}/srpmix-BUILD
    CTAGSDIR=${ROOTDIR}/ctags-TAGS
    LOGDIR=${ROOTDIR}/srpmix-LOG
    LOGFILE=${ROOTDIR}/srpmix-LOG/ctags-log.es


    if test ! -e ${CTAGSDIR}; then
	mkdir ${CTAGSDIR}
	status=$?

	if test $status != 0; then
	    echo "fail to create: ${CTAGSDIR}" 1>&2
	    abort
	fi
    elif test ! -d ${CTAGSDIR}; then
	echo "${CTAGSDIR} is not directory" 1>&2
	abort
    fi
}

function run_ctags
{
    d=$1
    o=$2
    l=$3


    es_print ctags-start --timestamp=\"`LANG=C date`\" --directory=\"$d\" --output=\"$o\" | tee -a $l
    find $d -type f \
	| egrep -v '/[^/]+\.[^/]+\.[^/]+$' \
	| grep -v .bz2           \
	| grep -v .gz            \
	| grep -v "${BLACKLIST}" \
	| ${CTAGS} -f $o -L -
    es_print ctags-end --status=$? --timestamp=\"`LANG=C date`\" --output=\"$o\" | tee -a $l
}

function verify_commands
{
    while [ $# -gt 0 ]; do
	if which $1 > /dev/null 2>&1; then
	    :
	else
	    echo "cannot find $1" 1>&2
	    abort
	fi
	shift 
    done
}

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}

function main
{
    o= 

    verify_commands "${CTAGS}"
    parse_arguments "$@"

    for d in ${BUILDDIR}/*; do
	o=${CTAGSDIR}/`echo ${d} | sed -e 's!'"${BUILDDIR}/"'!!'`.ctags
	run_ctags $d $o $LOGFILE
    done 
}


try_source ${LIBSRPMIX}
es_time main "$@"
exit $?

