#!/bin/sh
#
########################################################################
#
# srpmix-spider: Make symlinks of index files to package directories
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################


ROOTDIR=
LOGFILE=
LIBSRPMIX=libsrpmix.sh

function print_usage
{
    echo "Usage: "
    echo "  srpmix-spider [--help|-h]"
    echo "  srpmix-spider ROOTDIR"
    echo 
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}

function parse_arguments
{
    status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
    		print_usage
    		exit 0
    		;;
    	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    if test ! -d ${ROOTDIR}; then
	echo "no such directory: " "${ROOTDIR}" 1>&2
	abort
    fi
    
    LOGFILE=${ROOTDIR}/srpmix-LOG/spider-log.es
}




function spider_ln_s
{
    type=$1
    from="$2"
    to_file="$3"
    logfile="$4"

    if test ! -e ${to_file}; then
 	ln -s ${from} ${to_file}
 	es_print spider-link \
 	    --type=$type --from=\"${from}\" --to=\"${to_file}\" --status=$? \
 	    | tee -a ${logfile}
 	:
    else
 	:
    fi
}

function run_etags_spider
{
    pkg=
    from=
    to_dir=
    to_file=

    rootdir=$1
    builddir=${rootdir}/srpmix-BUILD
    etagsdir=${rootdir}/etags-TAGS
    etagfile=TAGS
    logfile=$2
    

    if test ! -d ${etagsdir}; then
	return 1
    fi

    for e in ${etagsdir}/*.etags; do
	pkg=`echo ${e} | sed -e "s+${etagsdir}/++" | sed -e "s/.etags//"`

	to_dir="${builddir}/${pkg}"
	to_file="${to_dir}/${etagfile}"
	from="../../etags-TAGS/${pkg}.etags"

 	if test -d ${to_dir}; then
 	    spider_ln_s etags "${from}" "${to_file}" "${logfile}"
 	else
 	    es_print spider-directory-not-exist \
 		--type=etags --directory=\"${to_dir}\" \
 		| tee -a ${logfile}
 	    :
 	fi
    done
    
    return 0
}

function run_ctags_spider
{
    pkg=
    from=
    to_dir=
    to_file=

    rootdir=$1
    builddir=${rootdir}/srpmix-BUILD
    ctagsdir=${rootdir}/ctags-TAGS
    ctagfile=tags
    logfile=$2
    

    if test ! -d ${ctagsdir}; then
	return 1
    fi

    for e in ${ctagsdir}/*.ctags; do
	pkg=`echo ${e} | sed -e "s+${ctagsdir}/++" | sed -e "s/.ctags//"`

	to_dir="${builddir}/${pkg}"
	to_file="${to_dir}/${ctagfile}"
	from="../../ctags-TAGS/${pkg}.ctags"

 	if test -d ${to_dir}; then
	    spider_ln_s ctags "${from}" "${to_file}" "${logfile}"
 	else
 	    es_print spider-directory-not-exist \
 		--type=ctags --directory=\"${to_dir}\" \
 		| tee -a ${logfile}
 	    :
 	fi
    done
    
    return 0
}

function run_cscope_spider
{
    pkg=
    from=
    to_dir=
    to_file=

    rootdir=$1
    builddir=${rootdir}/srpmix-BUILD
    cscopedir=${rootdir}/cscope-INDEX
    logfile=$2
    

    if test ! -d ${cscopedir}; then
	return 1
    fi

    for e in ${cscopedir}/*.cscope; do
	pkg=`echo ${e} | sed -e "s+${cscopedir}/++" | sed -e "s/.cscope//"`

	to_dir="${builddir}/${pkg}"
 	if test -d ${to_dir}; then
	    to_file="${to_dir}/cscope.out"
	    from="../../cscope-INDEX/${pkg}.cscope"
	    spider_ln_s cscope ${from} ${to_file} ${logfile}

	    to_file="${to_dir}/cscope.in.out"
	    from="../../cscope-INDEX/${pkg}.cscope.in"
	    spider_ln_s cscope ${from} ${to_file} ${logfile}

	    to_file="${to_dir}/cscope.po.out"
	    from="../../cscope-INDEX/${pkg}.cscope.po"
	    spider_ln_s cscope ${from} ${to_file} ${logfile}
	    :
 	else
 	    es_print spider-directory-not-exist \
 		--type=cscope --directory=\"${to_dir}\" \
 		| tee -a ${logfile}
 	    :
 	fi
    done
    
    return 0
}

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}

function main
{
    parse_arguments "$@"

    es_print spider-start \
	--type=etags \
	--rootdir=\"${ROOTDIR}\" \
	--timestamp=\"`LANG=C date`\" \
	>> ${LOGFILE}
    run_etags_spider ${ROOTDIR} ${LOGFILE}
    es_print spider-end \
	--type=etags \
	--rootdir=\"${ROOTDIR}\" \
	--timestamp=\"`LANG=C date`\" \
	>> ${LOGFILE}

    es_print spider-start \
	--type=ctags \
	--rootdir=\"${ROOTDIR}\" \
	--timestamp=\"`LANG=C date`\" \
	>> ${LOGFILE}
    run_ctags_spider ${ROOTDIR} ${LOGFILE}
    es_print spider-end \
	--type=ctags \
	--rootdir=\"${ROOTDIR}\" \
	--timestamp=\"`LANG=C date`\" \
	>> ${LOGFILE}

    es_print spider-start \
	--type=cscope \
	--rootdir=\"${ROOTDIR}\" \
	--timestamp=\"`LANG=C date`\" \
	>> ${LOGFILE}
    run_cscope_spider ${ROOTDIR} ${LOGFILE}
    es_print spider-end \
	--type=cscope \
	--rootdir=\"${ROOTDIR}\" \
	--timestamp=\"`LANG=C date`\" \
	>> ${LOGFILE}
}

try_source ${LIBSRPMIX}
es_time main $@
exit $?
