#!/bin/sh -e
########################################################################
#
# srpmix-hyperestraier: Create index for hyperestraier
#
# Copyright (C) 2009 Masato Taruishi
#
# Author: Masato Taruishi <taruishi@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
######################################################################

PATH=/bin:/usr/bin:/sbin:/usr/sbin

source libsrpmix.sh

SRPMIX_HYPERESTRAIER_INDEX_DIR=$SRPMIX_VAR_DIR/extra/hyperestraier/idx
SRPMIX_HYPERESTRAIER_CREATE_OPTIONS=-xh3
SRPMIX_HYPERESTRAIER_FILTER_DIR=/usr/share/hyperestraier/filter
SRPMIX_HYPERESTRAIER_GATHER_OPTIONS="-apn -cm -sd -ft -fx html H@$SRPMIX_HYPERESTRAIER_FILTER_DIR/estfxasis"

# list_files <source root dir>
function list_files() {

  if test -f "$1/plugins/file/file-i"; then
    cat "$1/plugins/file/file-i" |
      grep 'pre-build'  |
      grep -v ' image/' |
      grep -v ' application/x-elc' |
      grep -v ' application/octet-stream' |
      grep -v ' audio/' |
      grep -v ' video/' |
      cut -d: -f1 | sed 's!^\./!!'
  else
    ( cd $1 && find -L pre-build -not -type d )
  fi

}

if ! test -d "$SRPMIX_HYPERESTRAIER_INDEX_DIR"; then
  install -d $SRPMIX_HYPERESTRAIER_INDEX_DIR &&
	estcmd create $SRPMIX_HYPERESTRAIER_CREATE_OPTIONS \
		$SRPMIX_HYPERESTRAIER_INDEX_DIR
fi
find $SRPMIX_SOURCES_DIR/*/*/ -maxdepth 1 | 
	grep -v "/$" | while read d
do
  cd $d
  list_files . | estcmd gather $SRPMIX_HYPERESTRAIER_GATHER_OPTIONS $SRPMIX_HYPERESTRAIER_INDEX_DIR - || true
done

