#!/bin/sh
#
########################################################################
#
# srpmix-cscope: Make cscope indexes for files under srpmix dir
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

#
# In default cscope creates:
# - cscope.po.out
# - cscope.out
# - cscope.in.out
#
# With cscope -k -b -q -R -v -f ${PKG_NAME}.cscope -s${TARGET_SRC_DIR}
# - ${PKG_NAME}.cscope
# - ${PKG_NAME}.cscope.in
# - ${pkg_name}.cscope.po
#  

ROOTDIR=
CSCOPE=cscope

BUILDDIR=
CSCOPEDIR=
LOGDIR=
LOGFILE=
LIBSRPMIX=libsrpmix.sh


function print_usage
{
    echo "Usage: "
    echo "  srpmix-cscope [--help|-h]"
    echo "  srpmix-cscope ROOTDIR"
    echo 
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}

function parse_arguments
{
    status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    BUILDDIR=${ROOTDIR}/srpmix-BUILD
    CSCOPEDIR=${ROOTDIR}/cscope-INDEX
    LOGDIR=${ROOTDIR}/srpmix-LOG
    LOGFILE=${ROOTDIR}/srpmix-LOG/cscope-log.es


    if test ! -e ${CSCOPEDIR}; then
	mkdir ${CSCOPEDIR}
	status=$?

	if test $status != 0; then
	    echo "fail to create: ${CSCOPEDIR}" 1>&2
	    abort
	fi
    elif test ! -d ${CSCOPEDIR}; then
	echo "${CSCOPEDIR} is not directory" 1>&2
	abort
    fi
}

function run_cscope
{
    d=$1
    o=$2
    l=$3


    es_print cscope-start --timestamp=\"`LANG=C date`\" --directory=\"$d\" --output-dir=\"$o\" | tee -a $l
    ( cd $d && find */ -type f -name '*.[ch]' \
	| ${CSCOPE} -k -b -q -R -v -f "$o" -i- )
    es_print cscope-end --status=$? --timestamp=\"`LANG=C date`\" --output-dir=\"$o\" | tee -a $l
}

function verify_commands
{
    while [ $# -gt 0 ]; do
	if which $1 > /dev/null 2>&1; then
	    :
	else
	    echo "cannot find $1" 1>&2
	    abort
	fi
	shift 
    done
}

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}

function main
{
    o= 

    verify_commands "${CSCOPE}"
    parse_arguments "$@"

    for d in ${BUILDDIR}/*; do
	o=${CSCOPEDIR}/`echo ${d} | sed -e 's!'"${BUILDDIR}/"'!!'`.cscope
	run_cscope $d $o $LOGFILE
    done 
}


try_source ${LIBSRPMIX}
es_time main "$@"
exit $?
