#!/bin/sh

FLSERVER_PROG_DIR=$1
EMACS=$2

base_dir=${FLSERVER_PROG_DIR}
emacs=${EMACS}

if [ -n "${base_dir}" ]; then
    cd ${base_dir}
fi

if [ -z "${emacs}" ]; then
    emacs=emacs
fi

${emacs} -Q -l emacs/flserver.el
