#!/bin/bash -e
#
########################################################################
#
# srpmix-rootdir-attach: Make a root dir level plugin package
#
# Copyright (C) 2009 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
MY_TMPDIR=
PKG_NAME=
PKG_VERSION=0
PKG_RELEASE=0
OUTPUT_DIR=
ATTACHMENT=

SRPMIX_ROOTDIR_ATTACH_DEBUG=
YUM_OPTS=

DUMP_SPEC=


LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
        echo "*** ABORT..." "cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}

function print_usage
{
    echo "Usage: "
    echo "  srpmix-rootdir-attach [--help|-h]"
    echo "  srpmix-rootdir-attach [--debug] [--dump-spec] \\ "
    echo "                [--pkg-name=NAME] [--pkg-version=VER] [--pkg-release=REL] \\ "
    echo "                [--output-dir=DIR] [--yum=YUMOPT] \\"
    echo "                ATTACHMENT" 
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    (--help|-h) 
	        print_usage
	        exit 0
	        ;;
	    (--debug)
	        SRPMIX_ROOTDIR_ATTACH_DEBUG=yes
	        PS4="${PS4}[rootdir]"
	        set -x
		;;
	    (--dump-spec)
	        DUMP_SPEC=yes
	        ;;
	    (--pkg-name=*)
                PKG_NAME=${1/--pkg-name=}
		;;
	    (--pkg-version=*)
                PKG_VERSION=${1/--pkg-version=}
		;;
            (--pkg-release=*)
                PKG_RELEASE=${1/--pkg-release=}
		;;
	    (--output-dir=*)
	        OUTPUT_DIR=${1/--output-dir=}
		if ! test -d "${OUTPUT_DIR}"; then
		    srpmix_abort "No such directory: $OUTPUT_DIR"
		fi
		OUTPUT_DIR=$(cd $OUTPUT_DIR && pwd)
		;;
	    (--yum=*)
	        YUM_OPTS=$(echo $1 | sed 's/--yum=//')
		;;		
	    (--*|-*)
	        print_usage 1>&2
		srpmix_abort "Unknow option: $1"
		;;
	    (*)
	        break
		;;
	esac
	shift
    done
 
    if test $# -ne 1; then
	echo "*** Wrong number of arguments: " $# " (1 argument is expected)" 1>&2
	print_usage 1>&2
	exit 2
    fi

    ATTACHMENT="$1"
    if test -d "${ATTACHMENT}"; then
	ATTACHMENT=$(cd $1 && pwd)
    else
	:			# TODO
    fi
    shift 1

    : ${PKG_NAME:=$(basename ${ATTACHMENT})}
}

function create_spec
{
    local pkg_full_name=$1

    local rootdir=${SRPMIX_VAR_DIR}
    local distdir=${rootdir}
    local pluginsdir=${distdir}/plugins

    cat <<EOF
Summary:  $PKG_NAME plugin information for srpmix
Name: ${pkg_full_name}
Version: ${PKG_VERSION}
Release: ${PKG_RELEASE}%{?dist}
Source0: ${PKG_NAME}.tar
Autoreq: 0

Buildarch: noarch
Buildroot: %{_tmppath}/%{name}-root
BuildRequires: tar
Group: Software/Tools
License: Unknown

Requires: srpmix-dir-base

%define __os_install_post true

%description
$PKG_NAME plugin information for dist ${TARGET_DIST}

%prep
rm -rf \$RPM_BUILD_ROOT

%build

%install
rm -rf \$RPM_BUILD_ROOT
mkdir -p \$RPM_BUILD_ROOT/$pluginsdir

from=%{SOURCE0}
to=\$RPM_BUILD_ROOT/$pluginsdir
(cd \${to}; tar xf \${from})

%clean
chmod -R u+w \$RPM_BUILD_ROOT
rm -rf \$RPM_BUILD_ROOT

%files
%defattr(-,root,root)
${pluginsdir}/${PKG_NAME}

%changelog

EOF

}

function prepare_tarball
{
    local tarfile=$1
    cd $(dirname $ATTACHMENT)
    tar -c --to-stdout $(basename $ATTACHMENT) > $tarfile
}

function build_rpm
{
    if test "${SRPMIX_ROOTDIR_ATTACH_DEBUG}" = "yes"; then
	PS4="${PS4}[rpmbuild]"
    fi
    ${RPMBUILD} --define "_topdir $MY_TMPDIR" -ba ${spec_file}
}

function main
{
    local pkg_full_name
    local spec_file

    parse_arguments "$@"

    MY_TMPDIR=`mktemp -d`
    trap "/bin/rm -rf ${MY_TMPDIR}" 0

    if test -n "$SRPMIX_ATTACH_DEBUG"; then
	trap 0
	echo "*** Using $MY_TMPDIR as temporary directory for srpmix-rootdir-attach"
    fi

    pkg_full_name=srpmix-rootdir-${PKG_NAME}

    mkdir -p ${MY_TMPDIR}/SPECS
    spec_file=${MY_TMPDIR}/SPECS/${pkg_full_name}.spec
    create_spec ${pkg_full_name} > $spec_file
    if test -n "$DUMP_SPEC"; then
	cat $spec_file
	return 0
    fi

    mkdir -p ${MY_TMPDIR}/{RPMS,SRPMS,BUILD,BUILDROOT,SOURCES}
    (prepare_tarball ${MY_TMPDIR}/SOURCES/${PKG_NAME}.tar)

    (build_rpm ${spec_file})
    local rpm=${MY_TMPDIR}/RPMS/noarch/*.noarch.rpm
    if ! test -r ${rpm}; then
	srpmix_abort "*** Failed to create rpm file: $rpm" 2>&1
    fi
    
    if test -n "$OUTPUT_DIR"; then
	mkdir -p "$OUTPUT_DIR"
	mv ${rpm} "$OUTPUT_DIR"
	return $?
    else
	yum ${YUM_OPTS} localinstall -y --nogpgcheck ${rpm}
	return $?
    fi
}


time main "$@"
