#!/bin/bash

SCM=/usr/libexec/prelcopy/prelcopy.scm
CF=
OUTPUT_DIR=
CLASSES_DIR=/usr/libexec/prelcopy/classes

function print_usage
{
    echo "Usage: "
    echo "	$0 [--output-dir=OUTPUT-DIR] [--scm=PRELCOPY.SCM] [--classes-dir=CLASSES_DIR] CF.prelcopy"
    echo "	$0 --help"

    exit $1
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage 0
		;;
	    (--output-dir=*)
	        OUTPUT_DIR=${1/--output-dir=}
		if [ -d "${OUTPUT_DIR}" ]; then
		    OUTPUT_DIR=$(cd $OUTPUT_DIR; pwd)
		else
		    echo "No such directory: ${OUTPUT_DIR}" 2>&1
		    exit 1
		fi
	        ;;
	    (--scm=*)
	       SCM=${1/--scm=}
	       ;;
	    (--classes-dir=*)
	       CLASSES_DIR=${1/--classes-dir=}
	       ;;
	    --*)
		echo "No such option: $1" 1>&2 
		print_usage 1 1>&2
		;;
	    *)
		break
		;;
	esac
	shift 1
    done

    if [ -z "$1" ]; then
	print_usage 1 1>&2
    fi

    CF=$1
    shift 1

    if ! [ -z "$1" ]; then
	echo "Too many arguments" 1>&2
	print_usage 1 1>&2
    fi

    if ! [ -r $SCM ]; then
	echo "Cannot find prelcopy.scm" 1>&2
	exit 1
    fi

    if ! [ -d $CLASSES_DIR ]; then
	echo "Cannot find classes directory: $CLASSES_DIR" 1>&2
	exit 1
    fi
}

function main
{
    local classfile


    parse_arguments "$@"
  
    if ! source $CF; then
	exit 1
    elif [ -z "$PRELCOPY_CLASS" ]; then
	echo "No PRELCOPY_CLASS" 1>&2
	exit 1
    fi

    classfile="$CLASSES_DIR/$PRELCOPY_CLASS"    
    if ! [ -x "$classfile" ]; then
	echo "No such class: $classfile" 1>&2
	exit 1
    fi

    
    "$classfile" $CF | gosh $SCM $OUTPUT_DIR
}

main "$@"
