\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename intcs.info
@include version.texi
@settitle 詳解 Cluster2
@c @syncodeindex fn cp
@c @syncodeindex vr cp
@c @syncodeindex tp cp
@comment %**end of header

@dircategory Using Source code
@direntry
* 詳解 Cluster2: (intcs)       詳解 Cluster2
@end direntry

@titlepage
@title 詳解 Cluster2
@author Masatake YAMATO (@email{yamato@@redhat.com})
@page
@vskip 0pt plus 1filll
@c @insertcopying
@end titlepage

@ifnottex
@node Top
@top 詳解 Cluster2
本文章ではCluster2の内部構造について解説します。
ソースコードを活用してCluster 2のトラブルシューティングを実施するための
基礎となる知識の提供を目的とています。
@end ifnottex

@menu
* コンポーネントとパッケージの関係::
* ネットワーク通信レイヤ::
* コンポーネント間の通信経路::
* コンポーネントのステート::
* コンフィギュレーションの指定方法::
* ログの活用::
@end menu

@node コンポーネントとパッケージの関係
@chapter  コンポーネントとパッケージの関係
Cluster2は複数のパッケージに分割され、さらにそのパッケージのなかに複数
のコンポーネントが含まれています。コンポーネントにはツールやサービスデー
モンといった実行ファイルやライブラリが含まれます。

Cluster2が深遠だと感じる理由の一つは、協調して動作する目新しいコンポー
ネントが多数存在していることにあります。Cluster2について理解していくに
は、まずコンポーネントの名前を全て覚えてしまいましょう。各コンポーネン
トの役割については、この文章のなかで徐々に説明していきます。

@multitable @columnfractions .5 .5 .5
@cindex コンポーネント
@headitem コンポーネント @tab 種類 @tab 役割
@item aiexec
@tab サービスデーモン
@tab クラスターコア。メンバーシップと通信順序についてクラスター全体での合意を形成する。

@item service_cman.lcrso
@tab DLL
@tab aiexecに実行時に読み込まれるライブラリ。Quorumを提供する。

@item libcman.so
@tab DLL
@tab aiexecプロセスの外からservice_cman.lcrsoを利用するためのライブラリ

@item cman
@tab 起動スクリプト
@tab Cluster 2特有の設定の元でaiexecを起動します。
      
@item cman_tool
@tab コマンド
@tab XXX

@item ccsd
@tab サービスデーモン
@tab XXX

@item ccs_tool
@tab コマンド
@tab XXX

@item fenced
@tab サービスデーモン
@tab XXX

@item fenceエージェント
@tab コマンド
@tab XXX

@item groupd
@tab サービスデーモン
@tab XXX

@item group_tool
@tab コマンド
@tab XXX

@item qdiskd
@tab サービスデーモン
@tab XXX

@item rgmanager
@tab 起動スクリプト
@tab XXX

@item clurgmgrd
@tab サービスデーモン
@tab フェイルオーバーするサービスを監視、管理する

@item clurmtabd
@tab XXX        
@tab XXX

@end multitable


コンポーネントの名前を一通り覚えたら、次に各コンポーネントがどのパッケー
ジに所属しているかを把握しておきます。ログやpsコマンドの出力といったプ
ログラムの実行によって得られる情報においては、主にコンポーネントの名前
が使われます。一方ソースコードはパッケージを単位として編成されています。
従って実行によって得られた情報を元にソースコードを調査する場合、前もっ
て各コンポーネントがどのパッケージに所属しているか知っておくことが望ま
しいです。

@multitable @columnfractions .5 .5
@cindex パッケージ
@headitem パッケージ @tab 所属するコンポーネント

@item openais
@tab aixexec

@end multitable

@node ネットワーク通信レイヤ
@chapter ネットワーク通信レイヤ

Cluster2のネットワーク通信レイヤを下から順に記すと以下に記します。

@verbatim
ip
  udp
    corosync_totemnet
      corosync_totemsrp
        corosync_totempg
          openais_cman
            clvmd
            rgmanager
          openais_a
            openais_cpg
              groupd
            openais_evt
            openais_clm
          flowcontrol
          sync
@end verbatim




@node コンポーネント間の通信経路
@chapter コンポーネント間の通信経路

@node コンポーネントのステート
@chapter  コンポーネントのステート

@node コンフィギュレーションの指定方法
@chapter コンフィギュレーションの指定方法

@node ログの活用
@chapter ログの活用

@contents
@bye
