#!/bin/bash

GOSHIN_ARGS=
PKGCONFDIR=/etc/sstat
PKGDATADIR=/usr/share/sstat

GOSHIN=${GOSHIN:-${PKGDATADIR}/sstat-post.scm}


SOP_CONF_DIR=/etc/sop
if ! source "${SOP_CONF_DIR}/sop.cf"; then
    exit 1
fi

if ! [ -r "${GOSHIN}" ]; then
    echo "cannot find sstat-post.scm" 1>&2
    exit 1
fi

if ! [ -r "${PKGCONFDIR}/mapping.es" ]; then
    echo "cannot find mapping.es" 1>&2
    exit 1
fi


function print_usage
{
    local status=$1
    

    echo "Usage: " 
    echo "	$0 -h|--help"
    echo "	$0 [--reset] [--full-build]"

    exit $status
}


function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    (--help|-h)
	    print_usage 0
	    ;;
	    (--reset)
	    for x in \
		"${SOP_DIR}/"'sstat/user->date->package' \
		"${SOP_DIR}/"'sstat/package->user'       \
		"${SOP_DIR}/"'sstat/date->user->package' \
		; do
		if [ -d "$x" ]; then
		    echo "Removing target: $x"
		    rm -rf -I "$x"
		fi
	    done
	    ;;
	    (--full-build)
	    GOSHIN_ARGS="--full-build $GOSHIN_ARGS"
	    ;;
	    (*)
	    echo "wrong argument: $1" 1>&2
	    print_usage 1 1>&2
	    ;;
	esac
	shift
    done
}


function main
{
    parse_arguments "$@"

    gosh ${GOSHIN} \
	--data-dir="${SOP_ATTIC_DIR}/sstat" \
	--output-dir="${SOP_DIR}" \
	--mapping-file="${PKGCONFDIR}/mapping.es" \
	$GOSHIN_ARGS
}

main "$@"

