#!/bin/sh
#| -*- scheme -*- |#
:; exec gosh -- $0 "$@"
(use trapeagle.linux)
(use trapeagle.syscalls.fd)
(use trapeagle.syscalls.task)
(use gauche.parseopt)
(use util.match)

(define (show-help prog n)
  (format #t "~a --help\n" prog)
  (format #t "~a [--debug]\n" prog)
  (exit n))

(define control 
  (match-lambda*
   ((kernel 'report args)
    (report kernel args))))

(define (main args)
  (define (consume-one k r)
    (cond 
     ((eq? (car r) 'strace)
      (syscall k (cdr r)))
     ((eq? (car r)  'trapeagle)
      (control k (cadr r) (cddr r)))))
  (let-args (cdr args)
      ((help "h|help" => (cute show-help (car args) 0))
       (debug "debug" #t))
    (let ((kernel (make <linux>))
	  (extra (map read (map open-input-string (cdr args)))))
      (let loop ((r (read)))
	(unless (eof-object? r)
	  (consume-one kernel r)
	  (loop (read))))
      (for-each (pa$ consume-one kernel) extra)
      )))

