#!/bin/bash
FORMAT=grep
LIMIT=30
LOG=
XGETTEXTS=

function print_usage
{
    echo "Usage: "
    echo "	$0 --help|-h"
    echo "	$0 [--format=es|grep] [--limit=N] PATTERN|-|= XGETTEXT.OUT..."
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    (--format=*)
		FORMAT=${1/--format=}
		if [ "$FORMAT" = "es" ] || [ "$FORMAT" = "grep" ]; then
		    :
		else
		    print_usage 1>&2
		    exit 1
		fi
		;;
	    (--limit=*)
                LIMIT=${1/--limit=}
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if [ $# -lt 2 ]; then
	print_usage 1>&2
	exit 1
    fi

    LOG=$1
    shift
    XGETTEXTS=$@
}

function main
{
    parse_arguments "$@"
    
    {
	{ cat $XGETTEXTS | es-src-xgettext use-stdin; }
	if [ "$LOG" = "-" ]; then
	    gosh -e '(port-for-each (lambda (l) (write `(log ,l)) (newline)) read-line)'
	elif [ "$LOG" = "=" ]; then
	    cat
	else
	    echo "$LOG" | gosh -e '(begin (write `(log ,(read-line))) (newline))'
	fi
    } | {
	es-filter-filelines
    } | {
	if [ "$FORMAT" = "es" ]; then
	    cat
	elif [ "$FORMAT" = "grep" ]; then
	    es-filter-spout :filelines :fileline $LIMIT \
		| es-dest-grep '(:fileline :file)' '(:fileline :line)' '(:fileline :msg)' '(1)'
	else
	    :
	fi
    }
}

main "$@"