#!/bin/bash
#
########################################################################
#
# srpmix-coreutils: Create some core file statistics such as md5sum, wc
#
# Copyright (C) 2009 Masato Taruishi
#
# Author: Masato Taruishi <taruishi@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
NAME=coreutils

ROOTDIR=
MD5SUM=md5sum
WC=wc

BUILDDIR=
LOGFILE=
PLUGINDIR=

SRPMIX_COREUTILS_DEBUG=

FORCE=

LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}

function print_usage
{
    echo "Usage: "
    echo "  $0 [--help|-h]"
    echo "  $0 --name"
    echo "  $0 [--debug] [--plugin-dir=DIR] [--log-file=LOGFILE] [--force] [--name=NAME] ROOTDIR"
    echo 
}

function parse_arguments
{
    local status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    --name)
		echo $NAME
		exit 0
		;;
	    --name=*)
		NAME=${1/--name=}
		;;
	    --debug)
		set -x
		PS4="${PS4}[${NAME}]"
		SRPMIX_COREUTILS_DEBUG=yes
		;;
	    (--plugin-dir=*)
	        PLUGINDIR=${1/--plugin-dir=}
	        ;;
	    (--log-file=*)
	        LOGFILE=${1/--log-file=}
		;;
	    --force)
	        FORCE=yes
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	srpmix_abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    BUILDDIR=${ROOTDIR}/pre-build
    PLUGINDIR=${PLUGINDIR:-${ROOTDIR}/plugins/${NAME}}
    LOGFILE=${LOGFILE:-${PLUGINDIR}/${NAME}-log.es}

    if ! test -d "${BUILDDIR}"; then 
	exit 0
    fi

    if ! test -d "$PLUGINDIR"; then
        mkdir -p $PLUGINDIR
    fi
}

function run_cmd
{
    local d=$1
    local o=$2
    local l=$3
    local cmd=$4

    es_print "$cmd-start" --timestamp=\"`LANG=C date`\" --directory=\"$d\" --output=\"$o\" | tee -a $l
    cp /dev/null $o
    (cd $d && find . -not -type d \
	| grep -v ^./STATUS \
	| grep -v ^./SRPMIX \
	| grep -v ^./CRADLE \
	| grep -v ^.\$ \
	| grep -v ^./plugins \
	| grep -v ^./archives \
	| grep -v ^./vanilla \
	| grep -v ^./srpmix-LOG \
	| grep -v ^./srpmix-SPECS \
	| grep -v ^./SPECS \
	| grep -v ^./specs.spec \
	| xargs -d '\n' -n 1 $cmd >> $o )
    es_print "$cmd-end" --status=$? --timestamp=\"`LANG=C date`\" --output=\"$o\" | tee -a $l
}

function run_md5sum
{
    run_cmd $1 $2 $3 "${MD5SUM}"
}

function run_wc
{
    run_cmd $1 $2 $3 "${WC}"
}

function main
{
    parse_arguments "$@"
    srpmix_verify_commands "${MD5SUM}" "${WC}"

    if ( ! test -e "${PLUGINDIR}/md5sum" ) ||
	( test "${ROOTDIR}/STATUS" -nt "${PLUGINDIR}/md5sum" ) ||
	( test "$FORCE" = yes ) ; then
        run_md5sum "${ROOTDIR}" "${PLUGINDIR}/md5sum" $LOGFILE
    fi
    if ( ! test -e "${PLUGINDIR}/wc" ) ||
	( test "${ROOTDIR}/STATUS" -nt "${PLUGINDIR}/wc" ) ||
	( test "$FORCE" = yes ) ; then
        LANG=C run_wc "${ROOTDIR}" "${PLUGINDIR}/wc" $LOGFILE
    fi
}

es_time main "$@"
exit $?
