#!/bin/bash

CF=$1
NAME=$2
SBUILD_CONF=$3
SOP_CONF=$4
DATE=$5
DATE_FOR_LOG=$6

source ${SOP_CONF}

function main
{
    local cf=$1
    local name=$2
    
    local cradle_dir=${SOP_CRADLES_DIR}/${name}
    local cradle_dir=${SOP_CRADLES_DIR}/${name}
    local repo=${cradle_dir}/repo
    local mirror=${cradle_dir}/mirror
    local log=${cradle_dir}/log/envelop-${DATE_FOR_LOG}.log
    echo "not implemented yet" > ${log}
}

time main "$CF" "$NAME"