#!/bin/bash

# These parameters should be shared between before/after script.
TRAP_REQUESTS=/etc/strap/*.es
TMP_DIR=/var/tmp/strap

SOP_CF=/etc/sop/sop.cf
if ! source $SOP_CF; then
    echo "Failed to read $SOP_CF" 1>&2
    exit 1
fi

if [ -z "$SOP_DIR" ]; then
    echo "Cannot find SOP_DIR" 1>&2
    exit 1
fi

mkdir -p $TMP_DIR

for x in $TRAP_REQUESTS; do
    test -f $x && cat $x
done | gosh /usr/share/strap/strap.scm store $SOP_DIR $TMP_DIR
