#!/bin/sh
#| -*- scheme -*- |#
:; exec gosh -- $0 "$@"
(use sxml.serializer)
(use gauche.parseopt)

(define (show-help n)
  (format #t "Usage:\n")
  (format #t "	~a --help\n" *program-name*)
  (format #t "	~a < INPUT.SHTML > OUTPUT.HTML\n" 
	   *program-name*)
  (exit n))

(define (identity x) x)

(define (main args)
  (let-args (cdr args)
      ((help "h|help" => (pa$ show-help 0))
       . rest)
    (unless (null? rest)
      (with-output-to-port (current-error-port)
	(pa$ show-help 1)))
    (srl:sxml->xml-noindent (read) 
			    (current-output-port))))
