#!/bin/sh
#| -*- scheme -*- |#
:; exec gosh -- $0 "$@"

(use yogomacs.renderers.dired)
(use yogomacs.dentries.fs)
(use gauche.parseopt)
(use file.util)
(use font-lock.flclient)


(define (show-help n)
  (format #t "Usage:\n")
  (format #t "	~a --help\n" *program-name*)
  (format #t "	~a DIR\n" *program-name*)
  (format #t "	~a DIR > DIR.shtml\n" *program-name*)
  (format #t "	~a DIR | shtml->html > DIR.html\n" *program-name*)
  (exit n))

(define (main args)
  (let-args (cdr args)
      ((help "h|help" => (pa$ show-help 0))
       (css-output-dir "css-output-dir=s" "/tmp")
       . rest)
    (when (or (null? rest)
	      (< 1 (length rest)))
      (with-output-to-port (current-error-port)
	(pa$ show-help 1)))
    (let1 dir (car rest)
      (unless (file-is-directory? dir)
	(format (current-error-port)
		"No such directory: ~a\n" dir))
      (unless (file-is-readable? dir)
	(format (current-error-port)
		"Cannot read: ~a\n" dir))
      (let1 dentires (read-dentries dir #t #t #t
				    (lambda rest #t)
				    (lambda rest #t))
	(when dentires
	  (for-each
	   (cute flclient-cssize <> css-output-dir (list 'dired))
	   dired-faces)
	  (let1 shtml (dired dir dentires #f)
	    (write shtml)
	    ))
	(exit (if dentires 0 1))))))


