#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin
SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function backup0
{
    local name=$1
    local dir=$2

    mkdir -p ${SOP_BACKUP_DIR}/$name/$dir
    rsync -auvH ${SOP_CRADLES_DIR}/$name/$dir ${SOP_BACKUP_DIR}/$name/$dir 2>&1 \
	| tee "${SOP_CRADLES_DIR}/$name/log/backup-$dir-$date"
}
function backup
{
    local cf=$1/cf
    local name=$(basename $1)
    local date=$(date --rfc-3339=date)

    source $cf
    if test -z "$BACKUP"; then
	echo "No BACKUP in $cf" 1>&2
	return 1
    fi
    
    if test "$BACKUP" != yes; then
	return 0
    fi

    backup0 $name mirror $date
}

function main
{
    if test "x${SOP_ENABLE_BACKUP}" = x; then
	return 0
    fi

    
    for x in ${SOP_CRADLES_DIR}/*; do
	if test -d $x; then
	    ( backup "$x" )
	fi
    done
}

time main
