#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin
SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function hlink
{
    local cf=$1
    local name=$(basename $cf)

    source $cf

    if test -z "$BACKUP"; then
	echo "No BACKUP found in $cf" 1>&2
	return 1
    fi

    if test "$BACKUP" != yes; then
	return 0
    fi
    
    hardlink ${SOP_BACKUP_DIR}/mirror/${name}
}

function main
{
    local n

    for x in ${SOPCONFDIR}/mirror.d/*; do
	( hlink $x )
    done
}

time main
