#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin
CONF=sop.cf
REQDIR=srpmix-requests

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    source "$1/${CONF}"
elif test -f /etc/sop/${CONF}; then
    source /etc/sop/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi


function main
{
    local h 
    local p
    local s

    mkdir -p ${SOP_REQUESTS_DIR}

    for h in /home/*; do
	if test -d $h -a -d "$h/$REQDIR"; then
	    for p in $h/$REQDIR/*.src.rpm; do
		if test -r $p; then
		    s=$(basename $p)
		    if ! test -f ${SOP_REQUESTS_DIR}/$s; then
			# TODO hasing dir
			cp $p ${SOP_REQUESTS_DIR}
		    fi
		fi
	    done
	fi
    done
}

time main
