#!/bin/bash
#
########################################################################
#
# sop-080-hardlink-deployed --- Run hardlink on deployed source codes
#
# Copyright (C) 2008 Masato Taruishi
# Copyright (C) 2009 Masatake YAMATO
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# This code is drived from srpmix.daily in srpmix.
#
#
########################################################################

PATH=/bin:/usr/bin:/sbin:/usr/sbin
SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function main
{
    find ${SOP_SOURCES_DIR}/*/*/ -maxdepth 1 -mtime 0 \
	| grep -v "/\$"				      \
	| xargs -d '\n' -n1 dirname                   \
	| sort                                        \
	| uniq                                        \
	| xargs -d '\n' -n1 --verbose hardlink        
}

time main "$@"

