#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin
SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function hlink
{
    local cf=$1/cf
    local name=$(basename $1)

    source $cf

    if test -z "$ENABLE"; then
	echo "No ENABLE found in $cf" 1>&2
	return 1
    fi

    if test "$ENABLE" != yes; then
	return 0
    fi
    
    hardlink ${SOP_CRADLES_DIR}/${name}/mirror
}

function main
{
    local n

    for x in ${SOP_CRADLES_DIR}/*; do
	if test -d $x; then
	    ( hlink $x )
	fi
    done
}

time main
