#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin
SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function backup
{
    local cf=$1
    local name=$(basename $cf)

    source $cf
    if test -z "$BACKUP"; then
	echo "No BACKUP in $cf" 1>&2
	return 1
    fi
    
    if test "$BACKUP" != yes; then
	return 0
    fi
    
    mkdir -p ${SOP_BACKUP_DIR}/$name
    rsync -auvH ${SOP_MIRROR_DIR}/$name ${SOP_BAKCUP_DIR}/mirror/$name 2>&1 \
	|tee "/tmp/rsync-${name}.log"

}
function main
{
    if test "x${SOP_ENABLE_BACKUP}" = x; then
	return 0
    fi

    
    for x in ${SOPCONFDIR}/mirror.d/*; do
	( backup "$x" )
    done
}

time main
