#!/bin/bash 
cf=$1
log=$2

source $cf


if test -z "$USER_PATH"; then
    echo "No USER_PATH in $cf" 1>&2
    exit 1
fi

if test -z "$USER_PATTERN"; then
    echo "No USER_PATTERN in $cf" 1>&2
    exit 1
fi


for h in /home/*; do
    if test -d $h -a -d "$h/$USER_PATH"; then
	for p in "$h/$USER_PATH"/$USER_PATTERN; do
	    if test -r $p; then
		s=$(basename $p)
		if ! test -f ./$s; then
                    echo "import $p" >> $log
		    cp $p ./
		fi
	    fi
	done
    fi
done 
