#!/bin/bash 
cf=$1
log=$2

source $cf

if test -z "$FTP_HOST"; then
    echo "No FTP_HOST in $1" 1>&2
    exit 1
fi

if test -z "$FTP_PATH"; then
    echo "No FTP_PATH in $1" 1>&2
    exit 1
fi

if test -z "$FTP_PATTERN"; then
    echo "No FTP_PATTERN in $1" 1>&2
    exit 1
fi


wget -nH --cut-dirs=2 \
     --mirror "ftp://${FTP_HOST}${FTP_PATH}" \
     --accept "${FTP_PATTERN}" \
     -o ${log}
