#!/bin/bash
cf=$1
log=$2

source $cf

if test -z "$LCOPY_SYS_CONF_DIR"; then
    echo "No LCOPY_SYS_CONF_DIR in $cf" 1>&2
    exit 1
fi

if ! test -d "$LCOPY_SYS_CONF_DIR"; then
    return 0
fi

lcopy-update --root-dir=$(pwd)

ncpus=$(cat /proc/cpuinfo | grep processor | wc -l)

for c in "${LCOPY_SYS_CONF_DIR}"/*.lcopy; do
    echo "lcopy-checkout --sync-with-conf $c; exit 0" 
done | spawn -j${ncpus}
