#!/bin/bash
cf=$1
log=$2

source $cf

if test -z "$PRELCOPY_SYS_CONF_DIR"; then
    echo "No PRELCOPY_SYS_CONF_DIR in $cf" 1>&2
    exit 1
fi

if ! test -d "$PRELCOPY_SYS_CONF_DIR"; then
    return 0
fi

lcopy-update --root-dir=$(pwd)

MY_TMPDIR=`mktemp -d`
trap "chmod -R u+w $MY_TMPDIR; /bin/rm -rf $MY_TMPDIR" 0    

for c in "${PRELCOPY_SYS_CONF_DIR}"/*.prelcopy; do
    
    tmpdir=$MY_TMPDIR/$(basename $c .prelcopy)
    mkdir -p $tmpdir

    prelcopy --output-dir=$tmpdir $c 
    for f in $tmpdir/*.lcopy; do
    	if [ -f "$f" ]; then
            lcopy-checkout --sync-with-conf $f
	fi
    done
done
