#!/bin/bash

SOPCONFDIR=/etc/sop
CONF=sop.cf

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

FS=/tmp/sop-gc-fs
touch $FS
for x in ${SOP_SOURCES_DIR}/[0-9a-zA-Z]/*/*/pre-build; do
    if ! [[ "$x" =~ '.*\^.*' ]]; then
	echo $x | \
	    sed -e "s#${SOP_SOURCES_DIR}/[0-9a-zA-Z]/##" | \
	    sed -e "s#/pre-build##" | \
	    sed -e "s#/#-#" 
    fi
done | LANG=C sort | uniq > $FS

RPMS=/tmp/sop-gc-rpms
touch $RPMS
for x in $(rpm -qa | grep -e -srpmix | grep -v -e srpmix-plugin  | grep -v -e srpmix-archives | grep -v -e -lcopy-); do
    echo $x | sed -e 's/-srpmix.*$//'
done | LANG=C sort | uniq > $RPMS

MIRROR=/tmp/sop-gc-mirror
touch $MIRROR
for d in ${SOP_CRADLES_DIR}/*/mirror; do
    for s in $(find $d -type f | grep 'src.rpm$'); do
	rpm -qp --queryformat "%{NAME}-%{VERSION}-%{RELEASE}\n" $s
    done
done | LANG=C sort | uniq > $MIRROR

function report
{
    fs=$1
    rpms=$2
    mirror=$3
    
    echo FS level garbage:
    diff -ruN $rpms $fs | grep ^+[0-9a-zA-Z] | while read; do
	# Just rm
	
    done

    echo RPM level garbage:
    diff -ruN $mirror $rpms | grep ^+[0-9a-zA-Z] | while read; do
	echo $REPLY
    done
	 
}


report $FS $RPMS $MIRROR | tee /tmp/sop-gc-report
