#!/bin/bash

SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop


if test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function print_usage
{
    echo "Usage: "
    echo "	$0 --help|-h"
    echo "	$0 [MIRROR_NAME...]"
}

function mirror
{
    local cf=$1/cf
    local name=$(basename $1)

    source $cf
    if test -z "$METHOD"; then
	echo "No METHOD found in $cf" 1>&2
	return 1
    fi
    if test -z "$ENABLE"; then
	echo "No ENABLE found in $cf" 1>&2
	return 1
    fi
    if test -z "$GC"; then
	echo "No GC found in $cf" 1>&2
	return 1
    fi
    if test -z "$BACKUP"; then
	echo "No BACKUP found in $cf" 1>&2
	return 1
    fi
    if test -z "$DIST_MAPPING"; then
	echo "No DIST_MAPPING found in $cf" 1>&2
	return 1
    fi
    

    if test $ENABLE != yes; then
	return 0
    fi


    local handler="${PKGDATADIR}/mirror-${METHOD}"
    local ndir="${SOP_CRADLES_DIR}/${name}"
    local odir="${ndir}/mirror"
    local ldir="${ndir}/log"
    local date=$(date --rfc-3339=date)


    if ! test -x "${handler}"; then
	echo "No mirror handler for method: $method in $PKGDATADIR" 1>&2
	return 1
    fi

    if ! test -d $odir; then
	mkdir -p $odir
    fi

    if ! test -d $ldir; then
	mkdir -p $ldir
    fi


    cd ${odir}

    local log=${ldir}/mirror-${date}.log

    "${handler}" ${cf} "${log}"

    if [ -z "$BUILDERS" ]; then
	return
    fi

    # TODO: share the code
    if [[ "$BUILDERS" =~ ^srpmix$|,srpmix|srpmix,|,srpmix, ]]; then
	# TODO: This should be part of builder backend.
	find ${odir} -name '*.src.rpm'		\
	    | while read p; do dirname $p; done	\
	    | LANG=C sort				\
	    | uniq					\
	    > ${ndir}/.mirror-vpath
	mv -f ${ndir}/.mirror-vpath ${ndir}/mirror-vpath
	find ${odir} -name '*.src.rpm'		\
	    | while read p; do basename $p; done	\
	    | LANG=C sort			        \
	    | uniq					\
	    > ${ndir}/.mirror-pkgs
	mv -f ${ndir}/.mirror-pkgs ${ndir}/mirror-pkgs
    fi

    local dmap_dir=${ndir}/dist-mapping
    local mirror_dir=${odir}
    local dist_name
    mkdir -p "${dmap_dir}"
    if [ "${DIST_MAPPING}" = yes ]; then
	dist_name=${name}
	find "${mirror_dir}" -name '*.src.rpm' \
	    | srpmix-wrap --just-print \
	    > "${dmap_dir}/.${dist_name}.es"
	mv -f "${dmap_dir}/.${dist_name}.es" "${dmap_dir}/${dist_name}.es"
    elif [ "${DIST_MAPPING}" = no ]; then
	:
    else
	:
    fi

}

function main
{
    local name


    if [ "$#" = 1 ] && ( [ "$1" = "-h" ] || [ "$1" = "--help" ] ); then
	print_usage
	return 0
    fi

    if test $# = 0; then
	for d in ${SOP_CRADLES_DIR}/*; do
	    name=$(basename $d)
	    export SRPMIX_CRADLE_NAME="$name"
	    mirror $d
	done
    else
	for name in "$@"; do
	    local d="${SOP_CRADLES_DIR}/${name}"
	    if [ -d $d ]; then
		export SRPMIX_CRADLE_NAME="$name"
		mirror $d
	    fi
	done
    fi
}

time main "$@"
