#!/bin/bash

SOPCONFDIR=/etc/sop
CONF=sop.cf
OUTPUT_DIR=

function print_usage
{
    echo "Usage: "
    echo "	$0 [--help|-h] [--output-dir=DIR]"
}

if test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

source libsrpmix.sh || { 
    echo "Cannot load libsrpmix.sh file" 1>&2 
    exit 1
}


function report
{
    local fs=$1
    local swrfs=$2
    local mirror=$3
    
    local swrf_files=""


    echo '#' " @ File system level garbages:"
    diff -ruN $swrfs $fs | grep ^+[0-9a-zA-Z] | while read; do
	local candidate="${REPLY:1}"
	local c
	local swrfs_alive=no
	for c in ${SRPMIX_SWRFS_DIR}/${candidate:0:1}/${candidate}-*.swrf; do
	    if [ -f $c ]; then
		swrfs_alive=yes
		swrf_files="$swrf_files $candidate"
	    fi
	done
	if [ $swrfs_alive = no ]; then
	    

	    local v
	    echo "$candidate"
	    for v in "-srpmix" "-srpmix-archives" "-srpmix-plugins"; do
		echo "@rm -rf ${SRPMIX_DB_DIR}/${candidate:0:1}/${candidate}${v}"
	    done
	    (
		local c
		cd "${SOP_SOURCES_DIR}/${candidate:0:1}/"
		for c in */*; do
		    if [ "${c/\//-}" = "${candidate}" ]; then
			echo "@rm -rf ${SOP_SOURCES_DIR}/${candidate:0:1}/${c}"
		    fi
		done
	    )
	fi
    done
    
    echo '#' "Swrf file level garbages:"
    for c in $swrf_files; do
	echo $c
    done

    
    echo '#' "RPM level garbages:"
    diff -ruN $mirror $swrfs | grep ^+[0-9a-zA-Z] | while read; do
	echo ${REPLY:1}
    done
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    (--output-dir=*)
	    	OUTPUT_DIR=${1/--output-dir=}
		if [ -d "${OUTPUT_DIR}" ]; then
		    OUTPUT_DIR=$(cd $OUTPUT_DIR; pwd)
		else
		    echo "No such directory: ${OUTPUT_DIR}" 1>&2
		    exit 1
		fi
		;;
	esac
	shift
    done
}

function main
{
    local tempdir

    parse_arguments "$@"
    tempdir=`mktemp -d`
    if [ $? != 0 ]; then
	exit 1
    fi
    trap "chmod -R u+w $tempdir; /bin/rm -rf $tempdir" 0    

    
    local list_in_fs=/$tempdir/fs
    touch $list_in_fs

    for x in ${SOP_SOURCES_DIR}/[0-9a-zA-Z]/*/*/pre-build; do
	if ! [[ "$x" =~ .*\\^.* ]]; then
	    echo $x | \
		sed -e "s#${SOP_SOURCES_DIR}/[0-9a-zA-Z]/##" | \
		sed -e "s#/pre-build##" | \
		sed -e "s#/#-#" 
	fi
    done | LANG=C sort | uniq > $list_in_fs


    local list_swrf=/$tempdir/swrf
    touch $list_swrf

    for x in $(rpm -qa | grep -e -srpmix | grep -v -e srpmix-plugin  | grep -v -e srpmix-archives | grep -v -e -lcopy-); do
	echo $x | sed -e 's/-srpmix.*$//'
    done | LANG=C sort | uniq > $list_swrf


    local list_in_mirrors=/$tempdir/mirrors
    touch $list_in_mirrors
    for d in ${SOP_CRADLES_DIR}/*/mirror; do
	for s in $(find $d -type f | grep 'src.rpm$'); do
	    rpm -qp --nosignature --queryformat "%{NAME}-%{VERSION}-%{RELEASE}\n" $s
	done
    done | LANG=C sort | uniq > $list_in_mirrors


    local output
    if [ -n "$OUTPUT_DIR" ]; then
	local date=$(date --rfc-3339=date)
	output="${OUTPUT_DIR}/sop-gc-${date}"
    else
	output=/dev/stdout
    fi
    report $list_in_fs $list_swrf $list_in_mirrors > $output
}

time main "$@"
