#!/bin/bash

SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop


if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function print_usage
{
    echo "Usage: "
    echo "	sop-update [MIRROR_NAME...]"
}

function run_update
{
    local cf=$1
    local repo_name=$2
    local action=$3
    local force=$4
    
    source $cf

    if test -z "$GC"; then
	echo "No GC found in $cf" 1>&2
	return 1
    fi
    if test -z $INSTALL; then
	echo "No INSTALL found in $cf" 1>&2
	return 1
    fi

    if ( test $force != yes ) && ( test "$INSTALL" != yes ); then
	return 0
    fi

    yum -y --disablerepo='*' --enablerepo=${repo_name} ${action} '*srpmix*'
    if test $GC != yes; then
	return $?
    fi
    
    # TODO
    return 1
}
    
function main
{
    local cf
    local repo_name
    local protocol
    local mirror_name


    protocol=file


    if test $# = 0; then
	for n in ${SOP_CRADLES_DIR}/*; do
	    mirror_name=$(basename $n)
	    cf=${SOP_CRADLES_DIR}/${mirror_name}/cf
	    if ! test -f $cf; then
		continue
	    fi
	    repo_name=srpmix-$protocol-$(echo $mirror_name | tr '.' '-')
	    ( run_update "$cf" "$repo_name" "update" "no" )
	done
    else
	for mirror_name in "$@"; do
	    cf=${SOP_CRADLES_DIR}/$mirror_name/cf
	    if ! test -f $cf; then
		echo "No such mirror: $mirror_name" 1>&2
		continue
	    fi
	    repo_name=srpmix-$protocol-$(echo $mirror_name | tr '.' '-')
	    ( run_update "$cf" "$repo_name" "update" "yes" )
	done
    fi
}

main "$@"
