#!/bin/bash

SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop


if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function print_usage
{
    echo "Usage: "
    echo "	sop-update --help|-h"
    echo "	sop-update [MIRROR_NAME...]"
}

function run_yum
{
    local cf=$1
    local repo_name=$2
    local repo_file=$3
    local action=$4
    local force=$5
    
    source $cf

    if test -z $INSTALL; then
	echo "No INSTALL found in $cf" 1>&2
	return 1
    fi

    if ( test $force != yes ) && ( test "$INSTALL" != yes ); then
	return 0
    fi

    yum -y -c ${repo_file} --disablerepo='*' --enablerepo=${repo_name} ${action} '*srpmix*'
    return $?
}

function run_gc
{
    set -x

    MY_TMPDIR=`mktemp -d`
    trap "chmod -R u+w $MY_TMPDIR; /bin/rm -rf $MY_TMPDIR" 0    


    local cf=$1
    local mirror_name=$2
    local force=$3

    source $cf


    if test -z "$GC"; then
	echo "No GC found in $cf" 1>&2
	return 1
    fi

    if test "$GC" != yes; then
	return 0
    fi

    if test -z $INSTALL; then
	echo "No INSTALL found in $cf" 1>&2
	return 1
    fi

    if ( test $force != yes ) && ( test "$INSTALL" != yes ); then
	return 0
    fi

    local all=${MY_TMPDIR}/${mirror_name}-all.lines
    local weakview=${MY_TMPDIR}/${mirror_name}-weakview.lines
    local dist=${MY_TMPDIR}/${mirror_name}-dist.lines
    local packages=${MY_TMPDIR}/${mirror_name}-packages.lines


    rpm -qa --nosignature --queryformat "%{NAME} %{VERSION} %{RELEASE}\n" > ${all}
    grep weakview < ${all} > ${weakview}
    grep -e dist     < ${weakview} | grep -e ${mirror_name} | LANG=C sort -n -r > ${dist}
    grep -e packages < ${weakview} | grep -e ${mirror_name} | LANG=C sort -n -r > ${packages}

    local count=$(wc -l < ${dist})
    if test 0 = ${count} || test 1 = ${count}; then
	return 0
    fi

    local dist_car=$(head -1 ${dist} | tr ' ' '-')
    local dist_car_list=${MY_TMPDIR}/${mirror_name}-dist-car-list.lines
    local dist_cadr
    local dist_cadr_list=${MY_TMPDIR}/${mirror_name}-dist-cadr-list.lines
    local diff=${MY_TMPDIR}/${mirror_name}-diff
    local pkgs=${MY_TMPDIR}/${mirror_name}-pkgs
    local efiles_plugin=${MY_TMPDIR}/${mirror_name}-efiles-plugin
    local efiles_plugins=${MY_TMPDIR}/${mirror_name}-efiles-plugins
    local efiles_archives=${MY_TMPDIR}/${mirror_name}-efiles-archives
    local efiles_bases=${MY_TMPDIR}/${mirror_name}-efiles-bases

    rpm -ql ${dist_car} \
	| grep '/packages/./' \
	| xargs -n 1 readlink \
	| sed -e 's|.*/\([^/]*\)/\([^/]*\)$|\1 \2|' \
	> ${dist_car_list}

    touch ${efiles_plugin}
    touch ${efiles_plugins}
    touch ${efiles_archives}
    touch ${efiles_bases}

    tail -n +2 ${dist} | tr ' ' '-' | while read dist_cadr; do
	rpm -ql ${dist_cadr} \
	    | grep '/packages/./' \
	    | xargs -n 1 readlink \
	    | sed -e 's|.*/\([^/]*\)/\([^/]*\)$|\1 \2|' \
	    > ${dist_cadr_list}
	
	diff -uN ${dist_cadr_list} ${dist_car_list} | grep -e '^-[^-].*' | sed -e 's/^-//' >  ${diff}
	
	cat ${diff} | while read p0 vr0; do
	    fgrep -e "${p0}" ${all} | fgrep -e "${vr0}" > ${pkgs}
	    grep -e '.\+srpmix-plugin-.\+' ${pkgs}      | tr ' ' '-' | while read p; do
		echo ${p} >> ${efiles_plugin}
	    done
	    grep -e '.\+srpmix-plugins [0-9]' ${pkgs}     | tr ' ' '-' | while read p; do
		echo ${p} >> ${efiles_plugins}
	    done
	    grep -e '.\+srpmix-archives [0-9]' ${pkgs}    | tr ' ' '-' | while read p; do
		echo ${p} >> ${efiles_archives}
	    done
	    grep -e '.\+-srpmix [0-9]' ${pkgs} | tr ' ' '-' | while read p; do
		echo ${p} >> ${efiles_bases}
	    done
	done
	rpm -e ${dist_cadr}
    done

    LANG=C sort ${efiles_plugin}   | uniq | xargs rpm -e
    LANG=C sort ${efiles_plugins}  | uniq | xargs rpm -e
    LANG=C sort ${efiles_archives} | uniq | xargs rpm -e
    LANG=C sort ${efiles_bases}    | uniq | xargs rpm -e

    tail -n +2 ${packages} | tr ' ' '-' | while read n; do
	rpm -e "$n"
    done
}

function run
{
    local mirror_name=$1
    local protocol=$2
    local force=$3
    local cf
    local repo_file
    local repo_name
    local date=$(date --rfc-3339=date)
    local log


    cf=${SOP_CRADLES_DIR}/$mirror_name/cf
    if ! test -f $cf; then
	echo "No such mirror: $mirror_name" 1>&2
	return
    fi

    log=${SOP_CRADLES_DIR}/${mirror_name}/log/update-${date}.log

    repo_file=${SOP_CRADLES_DIR}/${mirror_name}/file.repo
    repo_name=srpmix-$protocol-$(echo $mirror_name | tr '.' '-')
    if ( run_yum "$cf" "$repo_name" "$repo_file" "install" $force ) > "${log}" 2>&1 ; then
	( run_gc "$cf" $(echo $mirror_name | tr '.' '-') $force ) >> "${log}" 2>&1
    fi
}
function main
{
    if [ "$#" = 1 ] && ( [ "$1" = "-h" ] || [ "$1" = "--help" ] ); then
	print_usage
	return 0
    fi

    local protocol

    protocol=file


    if test $# = 0; then
	for n in ${SOP_CRADLES_DIR}/*; do
	    mirror_name=$(basename $n)
	    run $mirror_name $protocol "no"
	done
    else
	for mirror_name in "$@"; do
	    run $mirror_name $protocol "yes"
	done
    fi
}

time main "$@"
