#!/bin/bash

SOPCONFDIR=/etc/sop
CONF=sop.cf

if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
    SOPCONFDIR=$1
    source "$1/${CONF}"
elif test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

FS=/tmp/sop-gc-fs
touch $FS
for x in ${SOP_SOURCES_DIR}/[0-9a-zA-Z]/*/pre-build; do
    if ! [[ "$x" =~ '.*\^.*' ]]; then
	echo $x
    fi
done | LANG=C sort > $FS

RPMS=/tmp/sop-gc-rpms
touch $RPMS
for x in $(rpm -qa | grep -e -srpmix | grep -v -e srpmix-plugin  | grep -v -e srpmix-archives); do
    echo $x
done | LANG=C sort > $RPMS

MIRROR=/tmp/sop-gc-mirror
touch $MIRROR
for d in ${SOP_CRADLES_DIR}/*/mirror; do
    for s in $(find $d -type f; | grep src.rpm); do
	rpm -qp --queryformat "%{PACAKGE} %{VERSION}-%{RELEASE}" $s
    done
done | LANG=C sort > $MIRROR