#!/bin/bash

SOPCONFDIR=/etc/sop
CONF=sop.cf
PKGDATADIR=/usr/share/sop


if test -f ${SOPCONFDIR}/${CONF}; then
    source ${SOPCONFDIR}/${CONF}
else
    echo "Cannot load ${CONF} file" 1>&2
    exit 1
fi

function print_usage
{
    echo "Usage: "
    echo "	$0 --help|-h"
    echo "	$0 [MIRROR_NAME...]"
}

function mirror
{
    local cf=$1/cf
    local name=$(basename $1)

    source $cf
    if test -z "$METHOD"; then
	echo "No METHOD found in $cf" 1>&2
	return 1
    fi
    if test -z "$ENABLE"; then
	echo "No ENABLE found in $cf" 1>&2
	return 1
    fi
    if test -z "$GC"; then
	echo "No GC found in $cf" 1>&2
	return 1
    fi
    if test -z "$BACKUP"; then
	echo "No BACKUP found in $cf" 1>&2
	return 1
    fi
    if test -z "$DIST_MAPPING"; then
	echo "No DIST_MAPPING found in $cf" 1>&2
	return 1
    fi
    

    if test $ENABLE != yes; then
	return 0
    fi


    local mirror_handler="${PKGDATADIR}/mirror-${METHOD}"
    local ndir="${SOP_CRADLES_DIR}/${name}"
    local odir="${ndir}/mirror"
    local ldir="${ndir}/log"
    local date=$(date --rfc-3339=date)


    if ! test -x "${mirror_handler}"; then
	echo "No mirror handler for method: $METHOD in $PKGDATADIR" 1>&2
	return 1
    fi

    if ! test -d $odir; then
	mkdir -p $odir
    fi

    if ! test -d $ldir; then
	mkdir -p $ldir
    fi


    cd ${odir}

    local mirror_log=${ldir}/mirror-${date}.log

    "${mirror_handler}" ${cf} "${mirror_log}"

    if [ -z "$BUILDERS" ]; then
	return
    fi

    # TODO: share the code
    if [[ "$BUILDERS" =~ ^srpmix$|,srpmix|srpmix,|,srpmix, ]]; then
	# TODO: This should be part of builder backend.
	find ${odir} -name '*.src.rpm'		\
	    | while read p; do dirname $p; done	\
	    | LANG=C sort				\
	    | uniq					\
	    > ${ndir}/.mirror-vpath
	mv -f ${ndir}/.mirror-vpath ${ndir}/mirror-vpath
	find ${odir} -name '*.src.rpm'		\
	    | while read p; do basename $p; done	\
	    | LANG=C sort			        \
	    | uniq					\
	    > ${ndir}/.mirror-pkgs
	mv -f ${ndir}/.mirror-pkgs ${ndir}/mirror-pkgs
    fi



    local dmap_dir=${ndir}/dist-mapping
    local dist_map_log=${ldir}/dist-map-${date}.log
    local dist_map_method


    mkdir -p "${dmap_dir}"

    if [ "${DIST_MAPPING}" = yes ]; then
	dist_map_method=srpms
    elif [ "${DIST_MAPPING}" = no ]; then
	dist_map_method=nop
    elif [ -z "${DIST_MAPPING}" ]; then
	dist_map_method=nop
    else
	dist_map_method=${DIST_MAPPING}
    fi

    local dist_map_handler="${PKGDATADIR}/dist-map-${dist_map_method}"
	
    if ! [ -x "${dist_map_handler}" ]; then
	echo "No dist map handler for method: ${dist_map_method} in ${PKGDATADIR}" 1>&2
	return 1
    fi
    ${dist_map_handler} ${cf} "${dist_map_log}"
}

function main
{
    local name


    if [ "$#" = 1 ] && ( [ "$1" = "-h" ] || [ "$1" = "--help" ] ); then
	print_usage
	return 0
    fi

    if test $# = 0; then
	for d in ${SOP_CRADLES_DIR}/*; do
	    name=$(basename $d)
	    export SRPMIX_CRADLE_NAME="$name"
	    mirror $d
	done
    else
	for name in "$@"; do
	    local d="${SOP_CRADLES_DIR}/${name}"
	    if [ -d $d ]; then
		export SRPMIX_CRADLE_NAME="$name"
		mirror $d
	    fi
	done
    fi
}

time main "$@"
