#!/bin/bash
#
########################################################################
#
# svnweb prelcopy class
#
# Copyright (C) 2009 Masafumi Miura
# Copyright (C) 2009 Masatake YAMATO
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

########################################################################

# SVNWEB_BASE_URL=url
SVNWEB_BASE_URL=

# SVNWEB_COMPONENT_LIST=(c0 c1 c2...)
declare -a SVNWEB_COMPONENT_LIST

# SVNWEB_PACKAGE_DICT[c]=PACKAGE
declare -A SVNWEB_PACKAGE_DICT

# SVNWEB_TYPES_DICT[c]="trunk tag"
declare -A SVNWEB_TYPES_DICT

# SVNWEB_TAG_ACCEPTABLE_REGEXP_DICT[c]=PATTERN
declare -A SVNWEB_TAG_ACCEPTABLE_REGEXP_DICT

function print_help
{
    echo "Usage: "
    echo "$0 PRELCOPY-FILE"
    exit $1
}

function handle_trunk
{
    local conf=$1
    local c
    local t
    local t0
    local p

    if [ -z "$SVNWEB_BASE_URL" ]; then
	echo "No value for SVNWEB_BASE_URL\n" 1>&2
	return 1
    fi

    for c in ${SVNWEB_COMPONENT_LIST[@]}; do
	t=${SVNWEB_TYPES_DICT[$c]}
	for t0 in $t; do
	    if [ "$t0" = trunk ]; then
		p=${SVNWEB_PACKAGE_DICT[$c]}
		if [ -z "$p" ]; then
		    p=$c
		fi
		cat <<EOF
(prelcopy :package "$p"
          :branch  "trunk"
          :command-line "svn checkout ${SVNWEB_BASE_URL}/$c/trunk"
	  :update #t
          :generated-by "${0##*/}+$conf")
EOF
	    fi
	done
    done
}

function acceptable_p
{
    local u=$1
    local c=$2

    [[ "$u" =~ ${SVNWEB_TAG_ACCEPTABLE_REGEXP_DICT[$c]} ]]
    return $?
}

function wash_branch
{
    echo $1 | tr . _
}

function handle_tag
{
    local conf=$1
    local c
    local b
    local d
    local t
    local t0
    local p
    local u


    if [ -z "$SVNWEB_BASE_URL" ]; then
	echo "No value for SVNWEB_BASE_URL\n" 1>&2
	return 1
    fi


    for c in ${SVNWEB_COMPONENT_LIST[@]}; do
	t=${SVNWEB_TYPES_DICT[$c]}
	
	for t0 in $t; do
	    if [ "$t0" = tag ]; then
	
		p=${SVNWEB_PACKAGE_DICT[$c]}
		if [ -z "$p" ]; then
		    p=$c
		fi
	    
		for u in $(curl -silent ${SVNWEB_BASE_URL}/$c/tags/ | \
		    sed -nre "s,.*href=\"([^\"]+)/\".*,\1,p"); do
		    
		    if acceptable_p "$u" "$c"; then
			b=$(wash_branch "$u")
			d="$u"
			cat <<EOF
(prelcopy :package "$p"
          :branch  "$b"
          :command-line "svn checkout ${SVNWEB_BASE_URL}/$c/tags/$d"
	  :update #f
          :generated-by "${0##*/}+$conf")
EOF
		    fi
		done
	    fi
	done
    done
}



function main
{
    if [ $# != 1 ]; then
	print_help 1 1>&2
    fi

    if ! source $1; then
	return $?
    fi

    if [ -z "$SVNWEB_COMPONENT_LIST" ]; then
	SVNWEB_COMPONENT_LIST=( "$SVNWEB_COMPONENT" )
	SVNWEB_PACKAGE_DICT["$SVNWEB_COMPONENT"]="$SVNWEB_PACKAGE"
	SVNWEB_TYPES_DICT["$SVNWEB_COMPONENT"]="$SVNWEB_TYPES"
	SVNWEB_TAG_ACCEPTABLE_REGEXP_DICT["$SVNWEB_COMPONENT"]="$SVNWEB_TAG_ACCEPTABLE_REGEXP"
    fi

    handle_trunk $(basename $1)
    handle_tag $(basename $1)

    return $?
}


main "$@"
