#!/bin/sh
#
########################################################################
#
# srpmix-etags: Run etags for files under srpmix dir
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

ROOTDIR=
ETAGS=etags

BUILDDIR=
ETAGSDIR=
LOGDIR=
LOGFILE=
PLUGINDIR=

LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}


BLACKLIST='.*\.bib$\|unic-005\.tex$\|.*\.srpmix$'

function print_usage
{
    echo "Usage: "
    echo "  srpmix-etags [--help|-h]"
    echo "  srpmix-etags ROOTDIR"
    echo 
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}

function parse_arguments
{
    status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    BUILDDIR=${ROOTDIR}/pre-build
    LOGDIR=${ROOTDIR}/srpmix-LOG
    LOGFILE=${ROOTDIR}/srpmix-LOG/etags-log.es
    PLUGINDIR=${ROOTDIR}/plugins/etags

    if ! test -d "$PLUGINDIR"; then
        mkdir -p $PLUGINDIR
    fi
}

function run_etags
{
    d=$1
    o=$2
    l=$3


    es_print etags-start --timestamp=\"`LANG=C date`\" --directory=\"$d\" --output=\"$o\" | tee -a $l
    (cd $d && find */ -type f \
	| egrep -v '/[^/]+\.[^/]+\.[^/]+$' \
	| grep -v .bz2           \
	| grep -v .gz            \
	| grep -v "${BLACKLIST}" \
	| ${ETAGS} -o $o - )
    es_print etags-end --status=$? --timestamp=\"`LANG=C date`\" --output=\"$o\" | tee -a $l
}

function verify_commands
{
    while [ $# -gt 0 ]; do
	if which $1 > /dev/null 2>&1; then
	    :
	else
	    echo "cannot find $1" 1>&2
	    abort
	fi
	shift 
    done
}

function main
{
    verify_commands "${ETAGS}"
    parse_arguments "$@"

    if test "${BUILDDIR}" -nt "${PLUGINDIR}/TAGS"; then
      install -d $LOGDIR
      run_etags "${BUILDDIR}" "${PLUGINDIR}/TAGS" $LOGFILE
    fi
}

es_time main "$@"
exit $?
