#!/bin/bash
#
########################################################################
#
# srpmix-vanilla: Expand compressed and/or archived files in SOURCES to VANILLA
#
# Copyright (C) 2007-2009 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
NAME=vanilla


ROOTDIR=

SOURCESDIR=
LOGFILE=
PLUGINDIR=


LIBSRPMIX=libsrpmix.sh

SRPMIX_VANIILA_DEBUG=

FORCE=

MY_TMPDIR=${TMPDIR}/tmp/srpmix-plugins-$(basename $0).$$
mkdir -p $MY_TMPDIR
trap "/bin/rm -rf $MY_TMPDIR" 0

function print_usage
{
    echo "Usage: "
    echo "  $0 [--help|-h]"
    echo "  $0 --name"
    echo "  $0 [--debug] [--plugin-dir=DIR] [--log-file=LOGFILE] [--force] ROOTDIR"
    echo 
}

function parse_arguments
{
    local status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    --name)
		echo $NAME
		exit 0
		;;
	    --debug)
		set -x
		PS4="${PS4}[${NAME}]"
		SRPMIX_VANIILA_DEBUG=yes
		;;
	    (--plugin-dir=*)
	        PLUGINDIR=${1/--plugin-dir=}
	        ;;
	    (--log-file=*)
	        LOGFILE=${1/--log-file=}
		;;
	    --force)
	        FORCE=yes
		# TODO, FORCE is not used now.
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	srpmix_abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    cd ${MY_TMPDIR}
    verify_directory ${ROOTDIR}

    SOURCESDIR=${ROOTDIR}/archives
    PLUGINDIR=${PLUGINDIR:-${ROOTDIR}/plugins/${NAME}}
    LOGFILE=${LOGFILE:-${PLUGINDIR}/${NAME}-log.es}

    if ! test -d "$PLUGINDIR"; then
        mkdir -p $PLUGINDIR
    fi
}

function run_vanilla
{
    local d=$1
    local o=$2
    local l=$3
    local report_to=/dev/null

    es_print vanilla-start --timestamp=\"`LANG=C date`\" --input=\"$d\" --output=\"$o\" | tee -a $l

    count=0
    for f in `find ${d} -type f`; do
	case "$f" in
	    *.tar.bz2|*.tbz|*.tbz2)
                count=`expr $count + 1`
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		(cd "$o"; tar jxvfm $f 2>&1 > ${report_to};
		    es_print vanilla-expand --command=\"tar\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
	    *.tar.gz|*.tgz|*.tar.Z)
                count=`expr $count + 1`
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		(cd "$o"; tar zxvfm $f 2>&1 > ${report_to};
		    es_print vanilla-expand --command=\"tar\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
	    # TODO: Is -X needed to update the file modification time?
	    *.zip)
	        count=`expr $count + 1`
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		(cd "$o"; unzip -o $f 2>&1 > ${report_to};
		    es_print vanilla-expand --command=\"unzip\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
  	    *.jar)
	        count=`expr $count + 1`
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		(cd "$o"; "${FASTJAR}" xf $f 2>&1 > ${report_to};
		    es_print vanilla-expand --command=\"jar\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
#	    *.shar.gz)
#               # shar.gz => GZIP=--best gunzip -c srpmix-3.104.0.shar.gz | unshar
#		;;
  	    *.gz|*.Z)
	        count=`expr $count + 1`
		local suffix
		case "$f" in
		    *.gz)
			suffix=.gz
			;;
		    *.Z)
			suffix=.Z
			;;
		esac
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		# --force is needed to decompress a file specified by a soft link.
		(cd "$o"; cat $f | gunzip --force - > $(basename $f $suffix) 2>${report_to};
		    es_print vanilla-expand --command=\"gunzip\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
  	    *.bz2)
	        count=`expr $count + 1`
		# --force is needed to decompress a file specified by a soft link.
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		(cd "$o"; bunzip2 --keep --stdout --force $f > $(basename $f .bz2) 2>${report_to};
		    es_print vanilla-expand --command=\"bunzip2\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
	    *.tar.lzma)
		count=`expr $count + 1`
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		(cd "$o"; unlzma --force --stdout $f > $(basename $f .lzma) &&
		    tar xfm $(basename $f .lzma); 
		    rm $(basename $f .lzma);
		    es_print vanilla-expand --command=\"lzma+tar\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
	    *.lzma)
	        count=`expr $count + 1`
		# --force is needed to decompress a file specified by a soft link.
		ln -s ../../archives/$(basename $f) "$o/`basename $f`"
		(cd "$o"; unlzma --force --stdout $f > $(basename $f .lzma)  &&
		    es_print vanilla-expand --command=\"lzma\" --input=\"$f\" --status=\"$?\" | tee -a $l)
		;;
	esac
    done
    es_print vanilla-end --count=${count} --timestamp=\"`LANG=C date`\" --output=\"$o\" | tee -a $l
    return 0
}

function verify_directory
{
    if test ! -d ${1}; then
	echo "*** ABORT...cannot find ${1}" '(' `pwd` ')'; 1>&2
	exit 1
    fi
}

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}

function main
{
    local o= 
    local count=0

    parse_arguments "$@"
    srpmix_verify_commands tar unzip fastjar gunzip bunzip2


    if test -d ${PLUGINDIR}; then
	count=$(ls ${PLUGINDIR} | wc -l)
    fi
    tmpdir=${PLUGINDIR}/.vanilla

    if test -d "${SOURCESDIR}" && test $count -eq 0; then
        test -d $tmpdir && /bin/rm -rf $tmpdir
	install -d $tmpdir
	
        # o=$tmpdir/`echo ${d} | sed -e 's!'"${SOURCESDIR}/"'!!'`
	o=$tmpdir
	run_vanilla ${SOURCESDIR} $o $LOGFILE
	srpmix_chmod $o 

	
	count=$(ls ${tmpdir} | wc -l)
	if test $count -gt 0; then
            mv $tmpdir/* "${PLUGINDIR}"
	fi
        /bin/rm -rf "$tmpdir"
    fi
}


try_source ${LIBSRPMIX}
es_time main "$@"
exit $?

