#!/bin/sh
#
########################################################################
#
# srpmix-kindex: Do make tags and make TAGS if the target is kernel
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

ROOTDIR=

SPEC=
PRE_BUILDDIR=
# LOGDIR=
# LOGFILE=
LIBSRPMIX=libsrpmix.sh

# TARGETS="i686 x86_64 ia64 ppc64"
TARGETS="i686 x86_64"


TMPDIR=/tmp/$(basename $0).$$
mkdir -p $TMPDIR
trap "/bin/rm -rf $TMPDIR" 0

function print_usage
{
    echo "Usage: "
    echo "  $0 [--help|-h]"
    echo "  $0 ROOTDIR"
    echo 
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}

function parse_arguments
{
    status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    verify_directory ${ROOTDIR}

    SPEC=${ROOTDIR}/*.spec
    PRE_BUILDDIR=${ROOTDIR}/pre-build
    PLUGINDIR=${ROOTDIR}/plugins/kindex
#    LOGDIR=${PLUGINDIR}/srpmix-LOG
#    LOGFILE=${LOGDIR}/kindex-log.es

}

function verify_commands
{
    while [ $# -gt 0 ]; do
	if which $1 > /dev/null 2>&1; then
	    :
	else
	    echo "cannot find $1" 1>&2
	    abort
	fi
	shift 
    done
}

function verify_directory
{
    if test ! -d ${1}; then
	echo "*** ABORT...cannot find ${1}" '(' `pwd` ')'; 1>&2
	exit 1
    fi
}

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}

function main
{
    verify_commands make etags ctags
    parse_arguments "$@"


    if ! grep '^Name: *kernel\(%.*\)\?$' $SPEC > /dev/null 2>&1; then
	return 0
    fi

# TODO: cscope, xen    
    if test -d "${PRE_BUILDDIR}" &&
       ( ! test -d "${PLUGINDIR}" ); then
	for t in $TARGETS; do
	    if test -d ${PRE_BUILDDIR}/*/*.${t}; then
		mkdir -p ${TMPDIR}/$t
		cd ${PRE_BUILDDIR}/*/*.${t}


		if ! make O=${TMPDIR}/$t TAGS; then
		    return
		fi
		
		make O=${TMPDIR}/$t tags
	    fi
	done
	
	mkdir -p "${PLUGINDIR}"
	for t in $TARGETS; do
	    mv ${TMPDIR}/$t/TAGS  ${PLUGINDIR}/${t}.TAGS
	    mv ${TMPDIR}/$t/tags  ${PLUGINDIR}/${t}.tags
	done
    fi
}


try_source ${LIBSRPMIX}
es_time main "$@"
exit $?

