#!/bin/sh
#
########################################################################
#
# srpmix-doxygen: Create doxygen documents
#
# Copyright (C) 2009 Masato Taruishi
#
# Author: Masato Taruishi <taruishi@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
NAME=doxygen


ROOTDIR=
DOXYGEN=doxygen

BUILDDIR=
ETAGSDIR=
LOGFILE=
PLUGINDIR=

SRPMIX_DOXGEN_DEBUG=

LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}

function print_usage
{
    echo "Usage: "
    echo "  $0 [--help|-h]"
    echo "  $0 --help"
    echo "  $0 [--debug] ROOTDIR"
    echo 
}

function parse_arguments
{
    status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    --name)
		echo $NAME
		exit 0
		;;
	    --debug)
		set -x
		PS4="${PS4}[doxygen]"
		SRPMIX_DOXGEN_DEBUG=yes
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	srpmix_abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    BUILDDIR=${ROOTDIR}/pre-build
    PLUGINDIR=${ROOTDIR}/plugins/doxygen
    LOGFILE=${PLUGINDIR}/doxygen-log.es

    if ! test -d "${BUILDDIR}"; then exit 0; fi

    if ! test -d "$PLUGINDIR"; then
        mkdir -p $PLUGINDIR
    fi
}

function run_doxygen
{
    d=$1
    o=$2
    l=$3

    es_print "doxygen-start" --timestamp=\"`LANG=C date`\" --directory=\"$d\" --output=\"$o\" | tee -a $l
    (cd $d &&
      ${DOXYGEN} -g - | 
        sed -e 's!^INPUT .*!INPUT=pre-build!' \
            -e "s!OUTPUT_DIRECTORY .*!OUTPUT_DIRECTORY=$o!" \
            -e "s!CREATE_SUBDIRS .*!CREATE_SUBDIRS=YES!" \
            -e "s!EXTRACT_ALL .*!EXTRACT_ALL=YES!" \
            -e "s!SOURCE_BROWSER .*!SOURCE_BROWSER=YES!" \
            -e "s!SHOW_DIRECTORIES .*!SHOW_DIRECTORIES=YES!" \
            -e "s!VERBATIM_HEADERS .*!VERBATIM_HEADERS=NO!" \
            -e 's!^RECURSIVE .*!RECURSIVE=YES!' |
      ${DOXYGEN} - 2>&1 ) | tee -a $l
    es_print "doxygen-end" --status=$? --timestamp=\"`LANG=C date`\" | tee -a $l
}

function main
{
    parse_arguments "$@"
    srpmix_verify_commands "${DOXYGEN}"

    if ( ! test -e "${PLUGINDIR}/html/index.html" ) ||
      test "${ROOTDIR}/STATUS" -nt "${PLUGINDIR}/html/index.html"; then
        run_doxygen "${ROOTDIR}" "${PLUGINDIR}" "$LOGFILE"
    fi
}

es_time main "$@"
exit $?
