#!/bin/bash
#
########################################################################
#
# srpmix-weakview-packages: Make packages->dist weak view
#
# Copyright (C) 2008 Masato Taruishi
#
# Author: Masato Taruishi <taruishi@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
        echo "*** ABORT..." "cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}



NAME=
OUTPUTDIR=
TMPDIR=
DUMP_SPEC=

# TODO: --srpm
function print_usage
{
    echo "Usage: "
    echo "  srpmix-weakview-packages [--help|-h]"
    echo "  srpmix-weakview-packages --name=NAME [--dump-spec]"
    echo "  srpmix-weakview-packages --name=NAME [--output-dir=OUTPUTDIR] [--release=RELEASE]"
    echo 
}

function cleanup
{
    if test -d "$TMPDIR"; then
        rm -rf $TMPDIR || true
    fi
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    --name=*)
                NAME="${1/--name=/}"
		;;
	    --output-dir=*)
	        OUTPUTDIR="${1/--output-dir=/}"
		;;
            --release=*)
	        SRPMIX_PKG_RELEASE="${1/--release=/}"
		;;
	    --dump-spec)
	        DUMP_SPEC=1
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test -z "$NAME"; then
	print_usage 1>&2
	srpmix_abort "No name for the weakview"
    fi

    if test -n "$1"; then
	print_usage 1>&2
	srpmix_abort "Too many arguments"
    fi

    if test -z "$OUTPUTDIR"; then
	OUTPUTDIR=.
    fi
    if test ! -d "${OUTPUTDIR}"; then
	srpmix_abort "No such directory: ${OUTPUTDIR}"
    fi
}

function create_packages_weakview
{
    name=$1
    shift

    spec=$TMPDIR/SPECS/srpmix-weakview-packages-$name.spec
    if test "x${DUMP_SPEC}" != "x"; then
	spec="/dev/stdout"
	if test ! -w "${spec}"; then
	    # ???
	    spec="/dev/tty"
	fi
    fi
	
    rootdir=${SRPMIX_VAR_DIR}
    sourcesdir=${rootdir}/sources
    packagesdir=${rootdir}/packages

    cat > $spec <<EOF
Summary: Srpmix weakview $name label to specfied version of packages
Name: srpmix-weakview-packages-$name
Version: $SRPMIX_PKG_VERSION
Release: $SRPMIX_PKG_RELEASE%{?dist}
Autoreq: 0
BuildRequires: srpmix
Buildarch: noarch
Requires: srpmix-dir-base

Buildroot: %{_tmppath}/%{name}-root
Group: System/Daemon
License: Unknown

%define __os_install_post true

%description
Srpmix weakview from packages to $name

%prep
rm -rf %{_builddir}/%{name}

%build
buildpackagesdir=%{_builddir}/%{name}${packagesdir}
mkdir -p \${buildpackagesdir}

EOF

# in %build
srpmix_distmap_to_pvr | while read package version release; do
  # Make link relative
  #seed=$(srpmix_srcdir $package $version $release | sed -e "s;$sourcesdir;;")
  seed=$(srpmix_srcdir $package $version $release)
  d="../../..${seed/$rootdir/}"
  sdir="$(dirname ${seed/$sourcesdir})"
  #sdir=${seed%/*}
  slink="$sdir/$name"
  echo "mkdir -p \${buildpackagesdir}${sdir}"
  echo "ln -sf $d \${buildpackagesdir}${slink}"
done >> $spec


    cat >> $spec <<EOF

%install
buildpackagesdir=%{_builddir}/%{name}${packagesdir}
rm -rf \$RPM_BUILD_ROOT
mkdir -p \$RPM_BUILD_ROOT/$packagesdir
rsync -va \$buildpackagesdir/* \$RPM_BUILD_ROOT/$packagesdir

%files
%defattr(-,root,root)
\$SRPMIX_VAR_DIR/packages/*/*/*

%changelog

EOF
    if test "x${DUMP_SPEC}" != "x"; then
	return
    fi

    $RPMBUILD --nodeps --quiet --define "_topdir $TMPDIR" -bs $spec > /dev/null
    rm -rf %{_builddir}/%{_builddir}/srpmix-weakview-packages-$name-$SRPMIX_PKG_VERSION-$SRPMIX_PKG_RELEASE*
    mv $TMPDIR/SRPMS/srpmix-weakview-packages-$name-$SRPMIX_PKG_VERSION-$SRPMIX_PKG_RELEASE*.src.rpm "${OUTPUTDIR}"
}


function main
{
    srpmix_verify_commands "${RPMBUILD}" "${GUILE}"
    parse_arguments "$@"

    if test "x${DUMP_SPEC}" = "x"; then
	TMPDIR=`mktemp -d`
	trap cleanup 0
	install -d $TMPDIR/{SPECS,BUILD,SOURCES,SRPMS}
    fi

    create_packages_weakview $NAME
}

RUN=
if test -z "${DUMP_SPEC}"; then
    RUN=es_time
fi
${RUN} main "$@"

exit $?
