#!/bin/sh
#
########################################################################
#
# srpmix-gonzui: Run gonzui for files under srpmix dir
#
# Copyright (C) 2007 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

ROOTDIR=
GONZUI=gonzui-import

BUILDDIR=
GONZUIDIR=
LOGDIR=
LOGFILE=
LIBSRPMIX=libsrpmix.sh

TMPDIR=/tmp/$0.$$
mkdir -p $TMPDIR
trap "/bin/rm -rf $TMPDIR" 0

EXCLUDE='\.srpmix$'

function print_usage
{
    echo "Usage: "
    echo "  srpmix-gonzui [--help|-h]"
    echo "  srpmix-gonzui ROOTDIR"
    echo 
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}

function parse_arguments
{
    status=


    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test $# -ne 1; then
	echo "wrong number of argument" 1>&2
	print_usage 1>&2
	abort
    fi

    ROOTDIR=$(cd $1;pwd)
    shift

    cd ${TMPDIR}
    verify_directory ${ROOTDIR}

    BUILDDIR=${ROOTDIR}/srpmix-BUILD
    GONZUIDIR=${ROOTDIR}/gonzui-DATABASE
    LOGDIR=${ROOTDIR}/srpmix-LOG
    LOGFILE=${ROOTDIR}/srpmix-LOG/gonzui-log.es


    if test ! -e ${GONZUIDIR}; then
	mkdir ${GONZUIDIR}
	status=$?

	if test $status != 0; then
	    echo "fail to create: ${GONZUIDIR}" 1>&2
	    abort
	fi
    elif test ! -d ${GONZUIDIR}; then
	echo "${GONZUIDIR} is not directory" 1>&2
	abort
    fi
}

# --exclude=PATTERN
# --db-dir=DIR
# TARGET
function run_gonzui
{
    target_dir=$1
    output_dir=$2
    log=$3


    es_print gonzui-start			\
	--timestamp=\"`LANG=C date`\"		\
	--target-directory=\"${target_dir}\"	\
	--output-directory=\"${output_dir}\"    \
	| tee -a "${log}"

    "${GONZUI}"                                 \
	--db-dir="${output_dir}"                \
	--exclude="${EXCLUDE}"                  \
	${target_dir}

    es_print gonzui-end				\
	--status=$?				\
	--timestamp=\"`LANG=C date`\"		\
	--target-directory=\"${target_dir}\"	\
	| tee -a "${log}"
}

function verify_commands
{
    while [ $# -gt 0 ]; do
	if which $1 > /dev/null 2>&1; then
	    :
	else
	    echo "cannot find $1" 1>&2
	    abort
	fi
	shift 
    done
}

function verify_directory
{
    if test ! -d ${1}; then
	echo "*** ABORT...cannot find ${1}" '(' `pwd` ')'; 1>&2
	exit 1
    fi
}

function try_source
{
    source $1
    if test $? != 0; then
	echo "*** ABORT...cannot find $1" 1>&2
	exit 1
    fi
}

function main
{
    o= 

    verify_commands "${GONZUI}"
    parse_arguments "$@"

    for d in ${BUILDDIR}/*; do
	run_gonzui $d ${GONZUIDIR} $LOGFILE
    done 
}


try_source ${LIBSRPMIX}
es_time main "$@"
exit $?
