#!/bin/bash
#
# srpmix-db --- Install SWRF, source codes wrapped in RPM Format 
#
RPM_PACKAGES=
COMMAND=
QUIET=


LIBSRPMIX=libsrpmix.sh
HARDLINK=${HARDLINK:=/usr/sbin/hardlink}

function try_source
{
    source $1
    if test $? != 0; then
        echo "*** ABORT..." "cannot find $1" 1>&2
	exit 1
    fi
}

function print_usage
{
    echo "Usage: "
    echo "  srpmix-db -h|--help"
    echo "  srpmix-db [--root=ROOT] [--quite|-q] -i|--install SWRF..."
    echo "  srpmix-db [--root=ROOT] [--quite|-q] -e|--erase|-e SWRF..."
    echo "  srpmix-db -l|--list"
    echo
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    -h|--help)
		print_usage
		exit 0
		;;
	    --root=*)
                srpmix_reset_var_dir ${1/--root=}
		shift 1
		;;
	    -q|--quiet)
		QUIET=yes
		shift 1
		;;
	    -i|--install)
		if test -z "$COMMAND"; then
		    COMMAND=install
		else
		    echo "COMMAND $COMMAND is already set" 1>&2
		    print_usage 1>&2
		    exit 1
		fi
		shift 1
		;;
	    -l|--list)
		if test -z "$COMMAND"; then
		    COMMAND=list
		else
		    echo "COMMAND $COMMAND is already set" 1>&2
		    print_usage 1>&2
		    exit 1
		fi
		shift 1
		;;
            -e|--erase)
		if test -z "$COMMAND"; then
		    COMMAND=erase
		else
		    echo "COMMAND $COMMAND is already set" 1>&2
		    print_usage 1>&2
		    exit 1
		fi
		shift 1
		;;
	    *)
		break
		;;
	esac
    done

    if test -z "$COMMAND"; then
	echo "no command is given" 1>&2
	print_usage 1>&2
	exit 1
    elif test x"$COMMAND" = xinstall; then
	RPM_PACKAGES="$@"
    elif test x"$COMMAND" = xerase; then
	RPM_PACKAGES="$@"
    elif test x"$COMMAND" = xlist; then
	:
    else
	:
    fi
}

function srpmix_db
{
    local package
    local name
    local hash

    if test ! -d "${SRPMIX_DB_RDIR}"; then
	:
    fi

    package=$1

    if test -f "$package"; then
	name="$(rpm -qp --queryformat %{NAME} $package)"
    else
	name=$package
    fi
    hash="$(srpmix_srchash "$name")"
    echo "${SRPMIX_DB_RDIR}/$hash/$name"
}

function do_install
{
    local db
    local count
    local max
    local pkgdir
    

    srpmix_verify_commands ${HARDLINK}


    count=0
    RPM_PACKAGES=$(echo "$RPM_PACKAGES" | tr ' ' '\n')
    max=$(echo "$RPM_PACKAGES" | wc -l)


    echo "$RPM_PACKAGES" | while read package; do
	db=$(srpmix_db $package)
	if test x"$QUIET" != xyes; then
	    echo "($count/$max) Installing...$(basename $package)"
	fi
	rpm --nodeps -Uvh --dbpath "$SRPMIX_VAR_DIR"/"$db" --relocate /="$SRPMIX_VAR_DIR" "$package"
	pkgdir=${SRPMIX_VAR_DIR}$(dirname $(rpm -qpl "$package"  | head -1))
	if test "x$pkgdir" != "x"; then
	    if test x"$QUIET" != xyes; then
		echo "($count/$max) Hardlink...$pkgdir/.."
	    fi
	    ${HARDLINK} $pkgdir/..
	fi
	count=$(expr $count + 1)
    done
    
}

function do_list
{
    for d in ${SRPMIX_DB_DIR}/[a-zA-Z0-9]; do
	echo ${d}
	for x in ${d}/*; do
	    if test -d ${x}; then
		echo "	$(basename ${x})"
	    fi
	done
	echo
    done
}

function do_erase
{
    local db
    local count
    local max
    
    count=0
    RPM_PACKAGES=$(echo "$RPM_PACKAGES" | tr ' ' '\n')
    max=$(echo "$RPM_PACKAGES" | wc -l)
    
    echo "$RPM_PACKAGES" | while read package; do
	db=$(srpmix_db $package)
	if test x"$QUIET" != xyes; then
	    echo "($count/$max) Deleting...$package"
	fi
	#
	if rpm --nodeps -e -dbpath "$SRPMIX_VAR_DIR"/"$db" "$package"; then
	    rm -rf "$SRPMIX_VAR_DIR/$db"
	else
	    :
	fi
	count=$(expr $count + 1)
    done
}

function main
{
    parse_arguments "$@"
    do_$COMMAND
}

try_source ${LIBSRPMIX}
main "$@"
exit $?
