#!/bin/sh -e
#
########################################################################
#
# srpmix-plugin: Run plugin scripts
#
# Copyright (C) 2008 Masato Taruishi
#
# Author: Masato Taruishi <taruishi@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
        abort "cannot find $1"
	exit 1
    fi
}
try_source ${LIBSRPMIX}


ROOTDIR=

function print_usage
{
    echo "Usage: "
    echo "  srpmix-plugin [--help|-h]"
    echo "  srpmix-plugin [--list-plugins|-L]"
    echo "  srpmix-plugin [<ROOTDIR> ...]"
    echo 
}

function abort
{
    echo "*** ABORT..." "$@" 1>&2
    exit 1
}

function list_source_dirs
{
    find $SRPMIX_SOURCES_DIR/*/*/ -maxdepth 1 | grep -v "/$"
}

function parse_arguments
{
    status=

    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
            --list-plugins|-L)
		list_plugins
		exit 0
		;;
	    *)
		break
		;;
	esac
	shift
    done

    ROOTDIRS="$@"
    if test "x$ROOTDIRS" = "x"; then
        ROOTDIRS=$(list_source_dirs)
    fi
}

function verify_commands
{
    while [ $# -gt 0 ]; do
	if which $1 > /dev/null 2>&1; then
	    :
	else
	    echo "cannot find $1" 1>&2
	    abort
	fi
	shift 
    done
}

function list_plugins
{
    find $SRPMIX_PLUGIN_DIR -perm +0100 -type f | sort | while read plugin
    do
        echo $plugin
    done
}

function main
{
    parse_arguments "$@"

    list_plugins | while read plugin
    do
        for d in $ROOTDIRS
        do
            $plugin $d
        done
    done
# TODO: return status, see srpmix-wrap
}


es_time main "$@"
exit $?
