#!/bin/sh
#
########################################################################
#
# srpmix-wrap: Wrap a target src.rpm to build srpmixed package
#
# Copyright (C) 2008 Masato Taruishi
#
# Author: Masato Taruishi <taruishi@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

RPMBUILD=rpmbuild

LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
        echo "*** ABORT..." "cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}


OUTPUTDIR=
TMPDIR=
JUST_PRINT=
DUMP_SPEC=
ALLOW_OVERWRITE=

function print_usage
{
    echo "Usage: "
    echo "  srpmix-wrap [--help|-h]"
    echo "  srpmix-wrap [--dump-spec|--just-print] [SRPMS...]"
    echo "  srpmix-wrap [--output-dir=OUTPUTDIR] [--release=RELEASE] [--allow-overwrite] [SRPMS...]"
    echo ""
    echo "  If SRPMS is not given, standard input is"
    echo "  used for the list of source packages."
    echo 
}

function cleanup
{
    if test -d "$TMPDIR"; then
        rm -rf $TMPDIR || true
    fi
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
	    --help|-h)
		print_usage
		exit 0
		;;
	    --output-dir=*)
	        OUTPUTDIR=$(echo $1 | sed 's/--output-dir=//')
		;;
            --release=*)
	        SRPMIX_PKG_RELEASE=$(echo $1 | sed 's/--release=//')
		;;
	    --just-print)
	        JUST_PRINT=1
		;;
	    --dump-spec)
	        DUMP_SPEC=1
		;;
	    --allow-overwrite)
	        ALLOW_OVERWRITE=1
		;;
	    *)
		break
		;;
	esac
	shift
    done

    if test "x$1" = "x"; then

            while read tmp; do
	  srpms="${srpms} ${tmp}"
	done
    else
	srpms=$@	
    fi

    if test "x${JUST_PRINT}" != "x" \
	-a "x${DUMP_SPEC}" != "x"; then
	print_usage 1>&2
	srpmix_abort "Specify either --just-print or --dump-spec"
    fi

    
    if test "x$OUTPUTDIR" = "x"; then
	OUTPUTDIR=.
    fi
    if test ! -d "${OUTPUTDIR}"; then
	srpmix_abort "No such directory: ${OUTPUTDIR}"
    fi
}

# A src.rpm is.
# => src.rpm for Foo is wrapped to srpmixed src.rpm by this function.
# ==> srpmixed rpm is created from srpmixed src.rpm by rpmbuild.
# ===> By Installing srpmixed rpm source files of Foo are deployed as if src.rpm for Foo is deployed 
#      by srpmix command.
#
# wrap_srpm srpm-file
#
function wrap_srpm
{
    target_srpm=$1
    spec=
    wrapped_name=
    es_name=

    pvrd=$(rpm -qp --nosignature --queryformat "%{NAME} %{VERSION} %{RELEASE} %{Description}" $target_srpm)
    package=$(echo $pvrd | cut -d' ' -f1)
    version=$(echo $pvrd | cut -d' ' -f2)
    release=$(echo $pvrd | cut -d' ' -f3)
    description="$(echo $pvrd | cut -d' ' -f4-)"
    if test "x$package" = "x"; then
        echo "warning: failed to parse $target_srpm: ignored" 1>&2
        return
    fi
    
    wrapped_name=$(srpmix_build_wrapped_name "$package" "$version" "$release")
    es_name=$(es_print srpmix-wrap name\
	--target-srpm="\"$(basename $target_srpm)\"" \
	--package="\"${package}\"" \
	--version="\"${version}\"" \
	--release="\"${release}\"" \
	--wrapped-name="\"${wrapped_name}\"")
    if test "x$JUST_PRINT" != "x"; then
	echo "$es_name"
	return
    fi
    
    if test -f ${OUTPUTDIR}/${wrapped_name}-$SRPMIX_PKG_VERSION-$SRPMIX_PKG_RELEASE*.swrf.src.rpm; then
	if test -z "$ALLOW_OVERWRITE"; then
            echo \;\; ${OUTPUTDIR}/${wrapped_name}-$SRPMIX_PKG_VERSION-$SRPMIX_PKG_RELEASE*.swrf.src.rpm already exists 1>&2
	    echo "$es_name"
            return
	fi
    fi
    
    group=$(rpm -qp --nosignature --queryformat "%{Group}" $target_srpm)
    license=$(rpm -qp --nosignature --queryformat "%{License}" $target_srpm)
#    changelog=$(LANG=C rpm -qp --nosignature --changelog $target_srpm | sed 's/%/%%/g')
#    if test "x$changelog" = "x(none)"; then
#        changelog=""
#    fi
    buildarch=$(rpm -qp --nosignature --queryformat "%{BUILDARCHS}" $target_srpm)
    if test "x$buildarch" = "x(none)"; then
        buildarch="noarch"
    fi

    srcdir=$(srpmix_srcdir $package $version $release)
    installdir=$(srpmix_installdir $package $version $release)

    if test "x${DUMP_SPEC}" = "x"; then
	spec="$TMPDIR/SPECS/${wrapped_name}.spec"
    else
	spec="/dev/stdout"
	if test ! -w "${spec}"; then
	    # ???
	    spec="/dev/tty"
	fi
    fi
    
    cat > "$spec" <<EOF
Summary: Source Information for package $package ($version-$release)
Name: ${wrapped_name}
Version: $SRPMIX_PKG_VERSION
Release: $SRPMIX_PKG_RELEASE%{?dist}.swrf
Source: `basename $target_srpm`
Autoreq: 0
BuildRequires: srpmix
BuildRequires: rsync
Buildarch: $buildarch

Buildroot: %{_tmppath}/%{name}-root
Group: $group
License: $license

%define __os_install_post true

%description
$description

%package archives
Group: $group
Summary: Source Archives for package $package ($version-$release)

%description archives
$description

%prep
if test -d %{_builddir}/%{name}; then 
  chmod -R u+w  %{_builddir}/%{name}
  rm -rf %{_builddir}/%{name}
fi

%build
srpmix-ix -f -v %{_builddir}/%{name} \
    %{_sourcedir}/`basename $target_srpm`
srpmix-plugin --enable=10srpmix-etags,90srpmix-file %{_builddir}/%{name}

%install
rm -rf \$RPM_BUILD_ROOT
mkdir -p \$RPM_BUILD_ROOT/$installdir

from=%{_builddir}/%{name}
to=\$RPM_BUILD_ROOT/$installdir
transfer_cmd=
if test \$(stat --format="%D" \$from) = \$(stat --format="%D" \$to); then
   transfer_cmd="cp -a -l"
else
   transfer_cmd="rsync -a"
fi
\$transfer_cmd \$(/bin/ls -d \$from/* | grep -v LOG | grep -v SPECS\$) \$to
mv \$RPM_BUILD_ROOT/$installdir/*.spec \$RPM_BUILD_ROOT/$installdir/specs.spec

%clean
chmod -R u+w \$RPM_BUILD_ROOT
rm -rf \$RPM_BUILD_ROOT

%files
%defattr(-,root,root)
# ${SRPMIX_VAR_DIR}
# ${SRPMIX_SOURCES_DIR}/
# ${SRPMIX_SOURCES_DIR}/*
# ${SRPMIX_SOURCES_DIR}/*/*
# ${SRPMIX_SOURCES_DIR}/*/*/*/
/${SRPMIX_SOURCES_RDIR}/*/*/*/SRPMIX
/${SRPMIX_SOURCES_RDIR}/*/*/*/STATUS
/${SRPMIX_SOURCES_RDIR}/*/*/*/pre-build
/${SRPMIX_SOURCES_RDIR}/*/*/*/plugins
/${SRPMIX_SOURCES_RDIR}/*/*/*/specs.spec

%files archives
%defattr(-,root,root)
# ${SRPMIX_SOURCES_DIR}/*/*/*/archives
/${SRPMIX_SOURCES_RDIR}/*/*/*/archives

%changelog
* Sat Jun  2 2007 SRPMIX WRAP <consulting-jp@redhat.com> $package-$version-$release
- Automatically generated.

EOF

    if test "x${DUMP_SPEC}" != "x"; then
	printf "# "
	echo "$es_name"
	return
    fi

    cp $target_srpm $TMPDIR/SOURCES/
    $RPMBUILD --quiet --define "_topdir $TMPDIR" -bs "$spec" > /dev/null
    mv $TMPDIR/SRPMS/${wrapped_name}-$SRPMIX_PKG_VERSION-$SRPMIX_PKG_RELEASE*.swrf.src.rpm "${OUTPUTDIR}"
    rm $TMPDIR/SOURCES/`basename $target_srpm`
    echo "$es_name"

    es_print srpmix-wrap done \
	--file="\"$(ls ${OUTPUTDIR}/${wrapped_name}-$SRPMIX_PKG_VERSION-$SRPMIX_PKG_RELEASE*.swrf.src.rpm)\""
}

function main
{
    srpmix_verify_commands "${RPMBUILD}"
    parse_arguments "$@"

    if test "x${JUST_PRINT}" = "x" \
	-o "x${DUMP_SPEC}" = "x"; then
	TMPDIR=`mktemp -d`
	trap cleanup 0
	install -d $TMPDIR/{SPECS,BUILD,SOURCES,SRPMS}
    fi

    for srpm in $srpms
    do
        if test -f "$srpm"; then
	    wrap_srpm "$srpm"
        else
            srpmix_abort "No such file: $srpm"
        fi
    done
}

RUN=
if test "x${DUMP_SPEC}" = "x"; then
    RUN=es_time
fi
${RUN} main "$@"

exit $?
