#!/bin/sh

TARGET_NAME=
TARGET_SRPM=

LIBSRPMIX=libsrpmix.sh
TMPDIR=
WRAP_OPTS=""
DEBUG=""

set -e


function print_usage
{
    echo "Usage: "
    echo "  srpmix [--release=RELEASE] [--debug]  --name=PACKAGE|--srpm=SRPM"
#    TODO: Multi targets
#    TODO: URL support
#    echo ""
#    echo "As SRPM a url like http://... is acceptable."
#
#    TODO: --git
#          --hg
#          --tgz
#          --dir
#  
}

function parse_arguments
{
    while [ $# -gt 0 ]; do
	case "$1" in
            --help|-h)
		print_usage
		exit 0
		;;
	    --name=*)
                TARGET_NAME="$(echo $1 | sed 's/--name=//')"
                ;;
	    --srpm=*)
	        TARGET_SRPM="$(echo $1 | sed 's/--srpm=//')"
		;;
	    --release=*)
	        WRAP_OPTS="$WRAP_OPTS --release=$(echo $1 | sed 's/--release=//')"
	        ;;
	    --debug)
	        DEBUG=yes
		;;
	    *)
	       break
	       ;;
	 esac
	 shift
    done
    
    if test "x$1" != "x"; then
	print_usage 1>&2
	srpmix_abort "too many arguments"
    fi

    if test -n "${TARGET_NAME}" -a -n "${TARGET_SRPM}"; then
	print_usage 1>&2
	srpmix_abort "Specify either --name or --srpm"
    fi

    if test -n "${TARGET_SRPM}"; then
	if test ! -f "${TARGET_SRPM}"; then
	    case "${TARGET_SRPM}" in
		http://*|ftp://*)
		    wget -O ${TMPDIR}/$(basename ${TARGET_SRPM}) ${TARGET_SRPM}
		    if test $? = 0; then
			TARGET_SRPM="${TMPDIR}/$(basename ${TARGET_SRPM})"
		    else
			srpmix_abort "Failed in download ${TARGET_SRPM}" 
		    fi
		    ;;
		*)
		    srpmix_abort "No way to retrieve ${TARGET_SRPM}"
		    ;;
	    esac
	else
	    TARGET_SRPM="${TMPDIR}/${TARGET_SRPM}"
	fi
    fi
}

function try_source
{
    source $1
    if test $? != 0; then
        echo "*** ABORT..." "cannot find $1" 1>&2
	exit 1
    fi
}

function main
{
    if test "`whoami`" != "root"; then
	srpmix_abort "You must be root to run this program"
    fi

    TMPDIR=`mktemp -d`
    trap "/bin/rm -rf $TMPDIR" 0    

    
    parse_arguments "$@"
    if test -n "$DEBUG"; then
	trap 0
	echo Using $TMPDIR as temporary directory
    fi

    cd $TMPDIR
    mkdir -p RPMS SRPMS BUILD
    
    
    if test -n "${TARGET_NAME}"; then
	yumdownloader --source "${TARGET_NAME}"
	TARGET_SRPM=$(/bin/ls *.src.rpm)
    fi

    for srpm in $TARGET_SRPM; do
	pvr=$(rpm -qp --queryformat %{NAME}-%{VERSION}-%{RELEASE} $srpm)
	srpmix-wrap $WRAP_OPTS $srpm
	rpmbuild --define "_rpmdir $TMPDIR/RPMS"     \
	         --define "_srcrpmdir $TMPDIR/SRPMS" \
	         --define "_builddir $TMPDIR/BUILD"  \
	         --rebuild -ba $pvr-srpmix-*.src.rpm \
        || exit 2
    done
    
    find RPMS/noarch -name '*noarch.rpm' | xargs yum localinstall -y --nogpgcheck

    #
    # TODO
    # 1. rename noarch.rpm -> swrf
    # 2. srpmix-envelop swrf
    # 3. rpmbuild
    # 4. yum localinstll
    #

    # find RPMS/noarch -name '*noarch.rpm' | xargs rpm -Uvh
    if test -n "$DEBUG"; then
	echo installed files are:
	find RPMS/noarch -name '*noarch.rpm'
    fi
    
}
try_source ${LIBSRPMIX}
main "$@"
exit $?
