#!/bin/bash -e
#
########################################################################
#
# srpmix-attach: Make a attachment swrf package
#
# Copyright (C) 2009 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

ATTACHMENT_VERSION=0
ATTACHMENT_RELEASE=0
ATTACHMENT_OUTPUT_DIR=.
ATTACHMENT_TYPE=
ATTACHMENT_NAME=
PKG_ATTACHED_TO=
VER_ATTACHED_TO=
ATTACHMENT_DATA_DIR=

LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
        echo "*** ABORT..." "cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}

function print_usage
{
    # srpmix-sttach --pkg-version= --pkg-release=N --output-dir= --type= --name=plugin-name package version data-directory 
}

function parse_arguments
{
}