#!/bin/bash -e
#
########################################################################
#
# srpmix-weakview-dist-attach: Make a dist level plugin package
#
# Copyright (C) 2009 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
MY_TMPDIR=
PKG_NAME=
PKG_VERSION=0
PKG_RELEASE=0
OUTPUT_DIR=
TARGET_DIST=
ATTACHMENT=
EXECUTABLE=

SRPMIX_WEAKVIEW_DIST_ATTACH_DEBUG=
YUM_OPTS=

DUMP_SPEC=


LIBSRPMIX=libsrpmix.sh
function try_source
{
    source $1
    if test $? != 0; then
        echo "*** ABORT..." "cannot find $1" 1>&2
	exit 1
    fi
}
try_source ${LIBSRPMIX}

function print_usage
{
    echo "Usage: "
    echo "  srpmix-weakview-dist-attach [--help|-h]"
    echo "  srpmix-weakview-dist-attach [--debug] [--dump-spec] \\ "
    echo "                [--pkg-name=NAME] [--pkg-version=VER] [--pkg-release=REL] \\ "
    echo "                [--output-dir=DIR] [--yum=YUMOPT] \\"
    echo "                [--srpmix-var-dir=DIR] \\ "
    echo "                DIST ATTACHMENT" 
    echo ""
    echo "ATTACHMENT: a directory or an executable."
    echo "             If it is a directory, it is used as an attachment directly."
    echo "             If it is an executable, the executable is invoked to create a "
    echo "             directory(ATTACHMENT-DIR), which is used as an attachment. " 
    echo "             The executable(EXE) is invoked with form: "
    echo ""
    echo "                    EXE DIST ATTACHMENT-DIR"
    echo ""
    echo "             Here ATTACHMENT-DIR is created by srpmix-weakview-dist-attach before "
    echo "             invoking EXE."
    echo ""
    echo "Environment variables:"
    echo "  SRPMIX_ROOT_USER"
}

function parse_arguments
{
    local r=0


    while [ $# -gt 0 ]; do
	case "$1" in
	    (--help|-h) 
	        print_usage
	        exit 0
	        ;;
	    (--debug)
	        SRPMIX_WEAKVIEW_DIST_ATTACH_DEBUG=yes
	        PS4="${PS4}[dist-attach]"
	        set -x
		;;
	    (--dump-spec)
	        DUMP_SPEC=yes
	        ;;
	    (--pkg-name=*)
                PKG_NAME=${1/--pkg-name=}
		;;
	    (--pkg-version=*)
                PKG_VERSION=${1/--pkg-version=}
		;;
            (--pkg-release=*)
                PKG_RELEASE=${1/--pkg-release=}
		;;
	    (--output-dir=*)
	        OUTPUT_DIR=${1/--output-dir=}
		if ! test -d "${OUTPUT_DIR}"; then
		    srpmix_abort "No such directory: $OUTPUT_DIR"
		fi
		OUTPUT_DIR=$(cd $OUTPUT_DIR && pwd)
		;;
	    (--srpmix-var-dir=*)
	        SRPMIX_VAR_DIR=${1/--srpmix-var-dir=}
		srpmix_reset_var_dir "$SRPMIX_VAR_DIR"
		;;
	    (--yum=*)
	        YUM_OPTS=$(echo $1 | sed 's/--yum=//')
		;;		
	    (--*|-*)
	        print_usage 1>&2
		srpmix_abort "Unknow option: $1"
		;;
	    (*)
	        break
		;;
	esac
	shift
    done
 
    if test $# -ne 2; then
	echo "*** Wrong number of arguments: " $# " (2 arguments are expected)" 1>&2
	print_usage 1>&2
	exit 2
    fi

    TARGET_DIST="$1"
    shift 1
    
    if [[ $TARGET_DIST =~ srpmix-weakview-dist-(.*) ]]; then
	$TARGET_DIST=${BASH_REMATCH[1]}
    fi

    ATTACHMENT="$1"
    if [ -d "${ATTACHMENT}" ]; then
	ATTACHMENT=$(cd $1 && pwd)
    elif [ -x "${ATTACHMENT}" ]; then
	EXECUTABLE=${ATTACHMENT}
	r=1
    elif [ -x "${SRPMIX_DIST_PLUGIN_DIR}/${ATTACHMENT}" ]; then
	EXECUTABLE="${SRPMIX_DIST_PLUGIN_DIR}/${ATTACHMENT}"
	r=1
    else
	echo "$ATTACHMENT is not a directory nor executable" 1>&2
	exit 3
    fi
    shift 1

    : ${PKG_NAME:=$(basename ${ATTACHMENT})}

    return $r
}

function create_spec
{
    local target_dist_full_name=$1
    local pkg_full_name=$2

    local rootdir=${SRPMIX_VAR_DIR}
    local distdir=${rootdir}/dists
    local target_distdir=${rootdir}/dists/${TARGET_DIST}
    local pluginsdir=${target_distdir}/plugins

    cat <<EOF
Summary:  $PKG_NAME plugin information for srpmix weakview dist ${TARGET_DIST}
Name: ${pkg_full_name}
Version: ${PKG_VERSION}
Release: ${PKG_RELEASE}%{?dist}
Source0: ${PKG_NAME}.tar
Autoreq: 0

Buildarch: noarch
Buildroot: %{_tmppath}/%{name}-root
BuildRequires: tar
Group: Software/Tools
License: Unknown

Requires: ${target_dist_full_name}

%define __os_install_post true

%description
$PKG_NAME plugin information for dist ${TARGET_DIST}

%prep
rm -rf \$RPM_BUILD_ROOT

%build

%install
rm -rf \$RPM_BUILD_ROOT
mkdir -p \$RPM_BUILD_ROOT/$pluginsdir

from=%{SOURCE0}
to=\$RPM_BUILD_ROOT/$pluginsdir
(cd \${to}; tar xf \${from})

%clean
chmod -R u+w \$RPM_BUILD_ROOT
rm -rf \$RPM_BUILD_ROOT

%files
%defattr(-,root,root)
${pluginsdir}/${PKG_NAME}

%changelog

EOF

}

function prepare_tarball
{
    local tarfile=$1
    cd $(dirname $ATTACHMENT)
    tar -c --to-stdout $(basename $ATTACHMENT) > $tarfile
}

function create_rpm
{
    if test "${SRPMIX_WEAKVIEW_DIST_ATTACH_DEBUG}" = "yes"; then
	PS4="${PS4}[rpmbuild]"
    fi
    ${RPMBUILD} --define "_topdir $MY_TMPDIR" -ba ${spec_file}
}

function main
{
    local target_dist_full_name
    local pkg_full_name
    local spec_file
    local need_invokation
    parse_arguments "$@"
    need_invokation=$?

    MY_TMPDIR=`mktemp -d`
    trap "/bin/rm -rf ${MY_TMPDIR}" 0

    if test -n "$SRPMIX_ATTACH_DEBUG"; then
	trap 0
	echo "*** Using $MY_TMPDIR as temporary directory for srpmix-weakview-dist-attach"
    fi


    #
    # DIST PLUGIN EXPECTED PROTOCOL
    #
    # ${EXECUTABLE} ${TARGET_DIST} "${ATTACHMENT}"
    #
    # Return 0 if it is successfully exected.
    #
    if [ $need_invokation != 0 ]; then
	ATTACHMENT=${MY_TMPDIR}/$(basename ${ATTACHMENT})
	mkdir -p "${ATTACHMENT}"
	if ! ${EXECUTABLE} ${TARGET_DIST} "${ATTACHMENT}"; then
	    echo "Failed to create attachment contents: ${EXECUTABLE} ${TARGET_DIST} ${ATTACHMENT}" 1>&2
	    return 1
	fi
    fi

    target_dist_full_name=srpmix-weakview-dist-${TARGET_DIST}
    pkg_full_name=${target_dist_full_name}-${PKG_NAME}

    mkdir -p ${MY_TMPDIR}/SPECS
    spec_file=${MY_TMPDIR}/SPECS/${pkg_full_name}.spec
    create_spec ${target_dist_full_name} ${pkg_full_name} > $spec_file
    if test -n "$DUMP_SPEC"; then
	cat $spec_file
	return 0
    fi

    mkdir -p ${MY_TMPDIR}/{RPMS,SRPMS,BUILD,BUILDROOT,SOURCES}
    (prepare_tarball ${MY_TMPDIR}/SOURCES/${PKG_NAME}.tar)

    (create_rpm ${spec_file})
    local rpm=${MY_TMPDIR}/RPMS/noarch/*.noarch.rpm
    if ! test -r ${rpm}; then
	srpmix_abort "*** Failed to create rpm file: $rpm" 2>&1
    fi
    
    if test -n "$OUTPUT_DIR"; then
	# TODO
	mkdir -p "$OUTPUT_DIR"/weakview
	mv ${rpm} "$OUTPUT_DIR"/weakview
	return $?
    else
	yum ${YUM_OPTS} localinstall -y --nogpgcheck ${rpm}
	return $?
    fi
}


time main "$@"
