#!/bin/bash

function main
{
    local action=$1
    local base_dir=$2
    mkdir -p ${base_dir}/plugins
    
    source ${base_dir}/checkout.lcopy
    local disable_args=$LCOPY_DISABLE_PLUGINS
    local enable_args=$LCOPY_ENABLE_PLUGINS
    
    local disable=vanilla
    local enable=

    if ! [[ "$disable_args" =~ nctags ]]; then
	enable=nctags
    fi

    if [ -n "$disable_args" ]; then
	disable="${disable},${disable_args}"
    fi

    if [ -n "$enable_args" ]; then
	enable="${enable},${enable_args}"
    fi

    if [[ "$action" = "noupdate" ]]; then
	# TODO: run only new plugins
	return
    fi

    # TODO: Check the existence of plugins specified with $enable 
    if which srpmix-plugin > /dev/null 2>&1; then
	srpmix-plugin --disable="${disable}" --enable="${enable}" ${base_dir}
    fi
}

main "$@"
