.TH TWIG 1 "December 4, 2008"

.SH NAME
twig \- manage a temporary branch for a package

.SH SYNOPSIS
twig fork NAME FROM [DIR]
.PP
twig info
.PP
twig diff [WITH]
.PP
twig specdiff [WITH]
.PP
twig pedigree
.PP
twig commit
.PP
twig build [\-ba|\-bb|\-bp|\-bc|\-bi|\-bl|\-bs] [BUILDID]
.PP
twig addlog MESSAGE [USER] [MAIL_ADDRESS]
.PP
twig help

.SH DESCRIPTION
