#!/bin/bash

TMP=`mktemp -d`

function extract
{
    (cd $TMP; cpio -id; find . | while read a; do
	    if file $a | grep ELF > /dev/null 2>&1; then
		echo $a
	    fi
     done)
}

function convert
{
    local i
    local o
    
    while read a; do
	i=$TMP/$a
	o=$1/$(echo $a | sed -e 's|\./|++|' -e 's|/|--|g')
	
	es $i $o
    done
}

function es
{
    cp $1 $2
}

function main
{

    local INPUT=$1
    local OUTPUT=$2

    trap "/bin/rm -rf $TMP" 0 


    if ! test -f "$INPUT"; then
	echo no such file: $INPUT 1>&2;
	exit 1
    fi

    if ! test -d "$OUTPUT"; then
	mkdir "$OUTPUT"
	if test "$?" != 0; then
	    exit 2
	fi
    fi


    rpm2cpio $INPUT | extract | convert $OUTPUT
}


main "$@"