#!/bin/bash

CVS_VERSION="0.0.0"
SUBCMDS="genconf help checkout"


#
# HELP
#
function cvs_cmd_help_help
{
    cvs_cmd_help
}

function cvs_cmd_help
{
    local subcmd=$1
    shift

    if [ -z "$subcmd" ]; then
	for s in $SUBCMDS; do
	    cvs_cmd_help_$s
	done
    else
	for s in $SUBCMDS; do
	    if [ $s = $subcmd ]; then
		cvs_cmd_help_$subcmd
		break
	    fi
	done
    fi
}

#
# GENCONF
# 
function cvs_cmd_help_genconf
{
    echo "	" cvs -d:pserver:USER:PASSWD@HOST 'checkout|co' MODULE 
    echo "	" cvs -d :pserver:USER:PASSWD@HOST 'checkout|co' MODULE 
    # 
    echo "	" cvs -d:extssh:USER@HOST 'checkout|co'  MODULE 
    echo "	" cvs -d :extssh:USER@HOST 'checkout|co'  MODULE 
    echo "	" '(do not use -P: -P is added automatically.)'
}

function cvs_cmd_genconf
{
    local original=$@
    local repo
    local module

    # 
    # -d REPO
    # 
    local drepo="$1"
    shift
    if [ -z "${drepo}" ]; then
	echo "broken cvs command line: too few argument" 1>&2
	cvs_cmd_help genconf 1>&2
	return 1
    elif [ "-d" = "$drepo" ]; then
	repo=$1
	shift 1
    elif [[ "${drepo}" == -d* ]]; then
	repo=${drepo/-d/}
    fi

    if [ -z "${repo}" ]; then
	echo "broken cvs command line: cannot find \"-d\" repository specification: $original" 1>&2
	return 1
    fi

    local pserver_sepc="^:pserver:[a-zA-Z0-9]+:[a-zA-Z0-9]*@[-a-zA-Z0-9./:]+$"
    local extssh_spec="^:extssh:[a-zA-Z0-9]+@[-a-zA-Z0-9./:]+$"
    if  ! ( [[ "$repo" =~ "$pserver_sepc" ]] || [[ "$repo" =~ "$extssh_spec" ]] ); then
	echo "broken cvs command line: unrecognizable repo specification: $repo" 1>&2
	echo "expected repo specifications: " 1>&2
	echo "	$pserver_sepc" 1>&2
	echo "	$extssh_sepc" 1>&2
	return 1
    fi

    #
    # COMMAND
    #
    local cmd=$1
    shift
    if [ -z "$cmd" ]; then
	echo "no command for checkout found" 1>&2
	return 1
    fi

    if ! ( [ "$cmd" = "co" ] || [ "$cmd" = "checkout" ] ); then
	echo "unknown command for checkout: $cmd" 1>&2
	return 1
    fi
    
    if [ "$1" = "-P" ] ; then
	shift 1
    fi

    #
    # MODULE
    #
    module=$1
    local module_spec="[-_+a-zA-Z0-9]+"
    shift

    if [ -z "$module" ]; then
	echo "NO MODULE given: $original" 1>&2
	return 1
    elif ! [[ "${module}" =~ "${module_spec}" ]]; then
	echo "unacceptable module name: ${module}" 1>&2
	echo "expected module specification: " 1>&2
	echo "	$module_spec" 1>&2
	return 1
    fi

    if [ "$1" = "-P" ] ; then
	shift 1
    fi

    if [ $# -gt 0 ]; then
	echo "too many argument: $@ IN $original" 1>&2
	return 1
    fi

    printf "CVS_CF_VERSION=\"%s\"\n" "${CVS_VERSION}"
    printf "CVS_REPOSITORY=\"%s\"\n" "${repo}"
    printf "CVS_MODULE=\"%s\"\n" "${module}"

    return 0
}

#
# CHECKOUT
#
function cvs_cmd_help_checkout
{
    echo "	" "cvs" "FILE.lcopy" "OUTPUT-DIR"
}

function cvs_cmd_checkout
{
    local input=$1
    local output_dir=$2

    if ! source "$input"; then
	return 1
    fi
    
    
    ( 
	cd ${output_dir}
	cvs -d"${CVS_REPOSITORY}" checkout -P "${CVS_MODULE}"
    )

    return $?
}

#
# UPDATE
#
function cvs_cmd_help_update
{
    echo "	" "cvs" "FILE.lcopy" "UPDATE-DIR"
}

function cvs_cmd_update
{
    local dir=$1
    local input=$2
    local update_dir=$3

    cd "${update_dir}"

    if cvs update -d | tee /tmp/cvs-update-$$; then
	if grep "^[MU] /tmp/cvs-update-$$ > /dev/null"; then
	    return 1
	else
	    return 0
	fi
    else
	return 2
    fi
}

function main
{
    local cmd=$1
    shift

    if [ -z "$cmd" ]; then
	echo "$0: no sub command given" 1>&2
    fi


    case "$cmd" in
	"help")	    
	    ;&
	"checkout")
            ;&
	"genconf")  
            cvs_cmd_"${cmd}" "$@"
	    return $?
            ;;
	*)
    esac
    
    
}

main "$@"
exit $?
