#!/bin/bash

BACKEND=hg
VERSION="0.0.0"

source liblcopy_backends.sh || exit 1

function write_spec
{
    local repo=$1

    common_write_spec 
    printf "HG_REPOSITORY=\"%s\"\n" "${repo}"
}

function repo_check
{
    local repo=$1

    if [ -z "${repo}" ]; then
	echo "broken hg command line: cannot find repository specification" 1>&2
	return 1
    fi

    local http_spec="^http://.*$"
    local https_spec="^https://.*$"
    if  ! ( [[ "$repo" =~ "$http_spec" ]]  || \
	    [[ "$repo" =~ "$https_spec" ]] ); then
	echo "broken hg command line: unrecognizable repo specification: $repo" 1>&2
	echo "expected repo specifications: " 1>&2
	for s in "$http_spec" "$https_spec" "$hg_spec"; do
	    echo "	$s" 1>&2
	done
	return 1
    else
	return 0
    fi
}

#
# HELP
#
function hg_help_help
{
    common_help_help "$@"
}

function hg_help
{
    common_help "$@"
}

#
# GENCONF_FORMAT
# 
function hg_genconf_format
{
    common_genconf_format "$@"
}

#
# GENCONF
# 
function hg_help_genconf
{
    local prefix

    if [ "$1" != "format" ]; then
	prefix="$0 genconf"
    fi

    echo "	" ${prefix} hg 'clone' URL
    echo "	" "(acceptable scheme for URL: http://..., and https://...)"
}

function hg_genconf
{
    local original=$@
    local cmd
    local repo


    if [ $# != 2 ]; then
	echo "wrong number of arguments: $original" 1>&2
	return 1
    fi


    cmd=$1
    shift
    if ! [ "$cmd" = "clone" ] ; then
	echo "unknown command for clone: $cmd" 1>&2
	return 1
    fi
    
    repo=$1
    shift
    if ! repo_check "${repo}"; then
	return 1
    fi
    write_spec "${repo}"
    return 0
}

#
# CHECKOUT
#
function hg_help_checkout
{
    echo "	$0 " "checkout" "FILE.lcopy" "OUTPUT-DIR"
}

function hg_checkout
{
    local input=$1
    local output_dir=$2

    if ! source "$input"; then
	return 1
    fi

    if [ -z "${HG_REPOSITORY}" ]; then
	echo "no HG_REPOSITORY in $input" 1>&2
	return 1
    fi

    ( 
	cd ${output_dir}

	common_spawn hg clone "${HG_REPOSITORY}"
    )

    return $?
}

#
# UPDATE
#
function hg_help_update
{
    echo "	$0 " "update" "FILE.lcopy" "UPDATE-DIR"
}

function hg_update
{
    local input=$1
    local update_dir=$2

    cd "${update_dir}"

    if common_spawn hg pull | tee /tmp/hg-update-$$; then
	if [ "$(wc -l < /tmp/hg-update-$$)" -gt 1 ] \
	   LANG=C grep  '^no changes found$' /tmp/hg-update-$$ > /dev/null 2>&1; then
	    return 0
	else
	    return 1
	fi
    else
	return 2
    fi
}

#
# DIRP
# 
function hg_help_dirp
{
    echo "	$0 " "dirp" "[DIR]"
}

function hg_dirp
{
    local dir=${1:-$(pwd)}
    
    test -d ${dir}/.hg
}

#
# REBIRTH
#
function hg_help_rebirth
{
    echo "	$0 " "rebirth" "[DIR]"
}

function hg_rebirth
{
    local dir=${1:-$(pwd)}

    if ! hg_dirp ${dir}; then
	echo "Not hg directory: ${dir} " 1>&2
	return 1
    fi


    local hg_url=$(hg showconfig -u paths.default)
    if [ $? != 0 ]; then
	echo "failed in hg config invocation (pwd: $(pwd))" 1>&2
	return 1
    fi

    local repo="${hg_url}"
    if ! repo_check "${repo}"; then
	return 1
    fi

    write_spec "${repo}"
}

function main
{
    common_main "$@"
    return $?
}

main "$@"
exit $?
