#!/bin/bash
METHOD=yum
ENABLE=yes
GC=yes
BACKUP=no
BUILD=no
BUILDERS=srpmix
DIST_MAPPING=yes
INSTALL=no

CREATEREPO_OPTS=

YUM_REPONAME=jpackage-generic
YUM_REPONAME_UPDATE=jpackage-generic-updates
YUM_REPOFILE=$(cat <<"EOF"
##
## Taken from http://www.jpackage.org/jpackage50.repo
##

# Be sure to enable the distro specific repository for your distro below:
# - jpackage-fc for Fedora Core
# - jpackage-rhel for Red Hat Enterprise Linux and derivatives

[jpackage-generic]
name=JPackage (free), generic
mirrorlist=http://www.jpackage.org/mirrorlist.php?dist=generic&type=free&release=6.0
failovermethod=roundrobin
gpgcheck=1
gpgkey=http://www.jpackage.org/jpackage.asc
enabled=1
timeout=1800

[jpackage-generic-updates]
name=JPackage (free), generic
mirrorlist=http://www.jpackage.org/mirrorlist.php?dist=generic&type=free&release=6.0-updates
failovermethod=roundrobin
gpgcheck=1
gpgkey=http://www.jpackage.org/jpackage.asc
enabled=1
timeout=1800

EOF
)
