\input texinfo @c -*-texinfo-*-

@comment %**start of header
@setfilename sdoc.info
@include version.texi
@settitle Using and building source code libraries
@c @syncodeindex fn cp
@c @syncodeindex vr cp
@c @syncodeindex tp cp
@comment %**end of header

@alias package = command
@alias cradle  = file

@setchapternewpage odd
@ifinfo
Copyright @copyright{} 2009 Masatake YAMATO
Copyright @copyright{} 2009 Red hat, K.K.
@end ifinfo

@dircategory Understanding source code
@direntry
* source code warehouseの利用と運用: (sdoc)       source code warehouseの利用と運用
@end direntry

@titlepage
@title source code warehouseの利用と運用
@author Masatake YAMATO (@email{yamato@@redhat.com})
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2009 Masatake YAMATO
Copyright @copyright{} 2009 Red hat, K.K.
@c @insertcopying
@end titlepage

@ifnottex
@node Top
@top source code warehouseの利用と運用
@end ifnottex

source code warehouseとは、あなたや同僚が読む可能性のあるソースコードがある
べきところに配置されていて、ダウンロード待ちもインストール待ちも無く、
捜す手間を最小限に、ソフトウェアの動作について疑問に思ったその瞬間すぐ
にソースコードリーディングを開始できるような作業環境を指す筆者の造語で
す。

そんな環境を実現できるでしょうか？

筆者はオープンソースソフトウェア群から成るOS、ミドルウェアに対するサポー
ト、コンサルテーション、トレーニングをサービスとして提供する会社に勤務
する傍ら、4年を費して擬似的なsource code warehouseを構築し、同僚とともに利用
しています。

「擬似的に」というのは以下のような意味です:

@itemize @bullet
@item 読む可能性のある全てのソフトウェアを知ることはできないので、業務の
範囲で読む可能性がありかつ一般に入手可能なものを対象とした。

@item 疑問に思った瞬間にソースコードリーディングを開始することはできな
いが、命名規則を十分に工夫したディレクトリ構造中にソースコードを配置し、
それをNFSで共有することで、職場のネットワークを利用している限り十分短い
時間で開始できるようにした。
@end itemize

本文章ではまず、既に構築されたsource code warehouseの利用方法を説明します。
私の同僚であれば、source code warehouseの利用方法だけを知っていれば、それだ
けで便利ははずです。

次に、source code warehouseの設置、運用手順について説明します。設置、運用は
プログラム(@package{sbuild}, @package{sop})を用いてある程度自動化できて
います。それらのプログラムと自動化が十分でない部分の注意について説明し
ます。設置されたsource code warehouseが無ければ自分で設置するしかありません。
設置したsource code warehouseにソースコードを追加していき規模が増してくると、
さまざまなトラブルが発生します。それらに対する対処方法も説明します。

最後にsource code warehouseの拡張方法を説明します。設置、運用プログラムには、
設置、運用処理のいつくかの箇所に、登録しておいたユーザ独自プログラムを
実行するためのフック、プラグイン機構が用意されています。その機構を利用し
てsource code warehouseの様々な側面を拡張できます。

@menu
* 利用(共有ファイルシステム上)::
* 利用(ホームディレクトリ内)::
* 設置と保守::
* 拡張::
@end menu

@c =====================================================================
@node 利用(共有ファイルシステム上)
@chapter 利用(共有ファイルシステム上)
「擬似的な」source code warehouseでは、十分に工夫した一貫した命名規則による
ディレクトリ構造中にソースコードファイルの配置しています。そしてそのトッ
プディレクトリをNFSで共有しています。

職場では@code{sources}という名前のホストがNFSサーバを担当しています。そ
こでこの文章でも@code{sources}という名前をホスト名に使うことにします。
早速マウントしてみましょう。

@example
# mkdir -p /srv/sources
# mount sources:/srv/sources /srv/sources
# cd /srv/sources
# ls
attic dists packages plugins sources
@end example

マウント先@file{/srv/sources}というマウント先は今のところ変更できません。
複数の目的でシンボリックリンクを取り回す必要があったため、その名前が設置用プログラムに
ハードコードされているためです。

@menu
* sources上のソースコード::
* トップレベルのディレクトリ構造::
* pvrのディレクトリ構造::
* pvr/pluginsのディレクトリ構造::
* attic/cradlesのディレクトリ構造::
@end menu

@node sources上のソースコード
@section sources上のソースコード
@code{sources}上にどういった種類のソースコードが配置されるか、というの
は設置時の設定によります。後に説明しますが、設置時の設定は
@file{/srv/sources/attic/cradles}以下に格納されます。ここでは筆者が職場
に設置したsourcesを例に説明します。

sources上には重複も含めて1.5Tバイトほどのソースコードがあります。次の表
に、ソースコードの取得先と取得対象種別、sourcesへの追加の方針を示します。

@multitable @columnfractions .4 .4 .2
@headitem 取得先 @tab 対象 @tab 追加方針

@item ftp.redhat.com                @tab *.src.rpm @tab non-gc
@item kojipkgs.fedoraproject.org    @tab *.src.rpm @tab gc
@item www.jpackage.org              @tab *.src.rpm @tab gc
@item rpmfusion-free-rawhide-source @tab *.src.rpm @tab gc
@item lcopy.sys                     @tab vcsによる @tab vcsによる

@end multitable

sources設置プログラム(@package{sbuild})の拡張機構を用いれば
@file{*src.rpm}以外の方法でまとめられたソースコードもsourcesに配置でき
るはずですが、もともとsourcesが筆者の業務に由来しているため、既に
sourcesに配置されているソースコードのほとんどが@file{*src.rpm}形式で入
手できるものばかりです。この@file{*src.rpm}を展開の後、有用そうな後処理
を加え、パッケージ間のディレクトリ名の衝突を避けて配置してあります。

運用ためのプログラム(@package{sop})は毎日取得先にある対象が更新されてい
ないか調べています。追加方針にgcとある場合、同名のパッケージに対するソー
スコードの新しいバージョンが取得先でみつかった場合、sources上にある古い
バージョンに対するソースコードを削除して、新しいものを配置します。
non-gcとある場合、古いバージョンを削除せずに、新しいバージョンを追加し
ます。

例えば @package{foo}というパッケージを考えます。sourcesには
@file{foo-1.1.src.rpm}のソースコードが既に配置済みだとします。ここで
fooの取得先にて@file{foo-1.2.src.rpm}の存在が検出されたとします。gcの場
合@file{foo-1.1.src.rpm}の内容を配置した @file{foo/1.1}を削除の後
@file{foo/1.2}を用意して、そこに@file{foo-1.2.src.rpm}の内容を配置しま
す。一方non-gcの場合@file{foo/1.1}をそのままにして、@file{foo/1.2}を用
意して、そこに@file{foo-1.2.src.rpm}の内容を配置します。

@cradle{ftp.redhat.com}は、最も業務で頻繁に用いるはずです。最近アップデー
トされたパッケージよりは、(顧客の使う)古いバージョンに関する調査が頻発
するので追加方針をnon-gcとしています。

@cradle{kojipkgs.fedoraproject.org}, @cradle{www.jpackage.org},
@cradle{rpmfusion-free-rawhide-source}は、必ずしも業務に必要ないかもし
れませんが、最近のオープンソース世界の動向や、将来の製品候補のコードレ
ベルで調査するのに役立つはずです。

@cradle{lcopy.sys}は変り種です。唯一対象を@file{*src.rpm}としません。
@cradle{lcopy.sys}はソースコードの入手に@command{git}, @command{svn},
@command{cvs}といったバージョン管理システムを使います。入手先となるリポ
ジトリはsources構築時に指定します。最初にチェックアウトして、以降毎日アッ
プデートします。現状では、linuxカーネルの開発元であるgit.kernel.orgなど
がリポジトリとして指定されています。特定のソフトウェアの最新動向を追跡
することができます。

入手先がどこであれ、十分に工夫した一貫した命名規則によるディレクトリ構
造中にソースコードファイルを配置しているため、どのソフトウェア(あるいは
パッケージ)のソースコードであれ、それを@file{/srv/sources}からみつける
のは容易です。以降その命名規則を説明します。

@node トップレベルのディレクトリ構造
@section トップレベルのディレクトリ構造
トップレベルである@file{/srv/sources}には
@file{sources}, @file{packages}, @file{dists}, @file{plugins}, @file{attic}
の5つのディレクトリがあります。

@menu
* sources ディレクトリ::
* dists ディレクトリ::
* packages ディレクトリ::
* plugins ディレクトリ::
* attic ディレクトリ::
@end menu

@node sources ディレクトリ
@subsection sources ディレクトリ
ソースコードを参照したいパッケージの名前とバージョンについて正確に知っている場合、
@file{sources}を使います。

あるパッケージの名前を@emph{package-name}、バージョンを@emph{version-release}、
パッケージの名前の最初の文字を@emph{p}としたとき、そのソースコードは以下の場所
に配置されます。

@cartouche
@example
/srv/sources/sources/@emph{p}/@emph{package-name}/@emph{version-release}
@end example
@end cartouche


@node dists ディレクトリ
@subsection dists ディレクトリ

@node packages ディレクトリ
@subsection packages ディレクトリ

@node plugins ディレクトリ
@subsection plugins ディレクトリ

@node attic ディレクトリ
@subsection attic ディレクトリ


@node pvrのディレクトリ構造
@section pvrのディレクトリ構造

specs.spec
pre-build
archives
vanilla
plugins

@node pvr/pluginsのディレクトリ構造
@section pvr/pluginsのディレクトリ構造

@node attic/cradlesのディレクトリ構造
@section attic/cradlesのディレクトリ構造

@node 利用(ホームディレクトリ内)
@chapter 利用(ホームディレクトリ内)

@node 設置と保守
@chapter 設置と保守
srpmix, sop, sbuild, lcopy

@node 拡張
@chapter 拡張
srpmix: spec rewrite rules, package-plugins, dist-plugin, top-plugin
sbuild: builder
sop: mirror-engine
lcopy: backend

@contents
@bye
