(add-hook find-file-pre-hook focus)
(add-hook find-file-post-hook (pa$ jump-lazy (js-field (js-field *js* "location") "hash")))
(add-hook find-file-post-hook require-yarns)
(add-hook find-file-post-hook (lambda ()
				(let1 original-prompt #f
				  (let1 options (alist->object `((ghosting . #f)
								 (revert . #t)
								 (onStart . ,(lambda (draggable event)
									       (let1 prompt ($ "minibuffer-prompt")
										 (set! original-prompt prompt.innerHTML)
										 (prompt.update (<- "minibuffer")))))
								 (onEnd . ,(lambda (draggable event)
									     (let1 prompt ($ "minibuffer-prompt")
									       (prompt.update  original-prompt)
									       )))))
				    (js-new Draggable "minibuffer-prompt" options)))
				(let1 options (alist->object `((accept . "*")))
				  (($$ ".lfringe").each (lambda (id) (Droppables.add id.id options)))
				)))