#!/bin/bash

CC=/usr/bin/_cc
declare -a rep

D="-D__OPTIMIZE__=1 -U__NO_INLINE__"
O0=-O0
g3=-g3

function pid_trace
{
    local i
    local v=

    i=$$
    while true; do
	v=(`sed -n -e 's/^\(Pid\|PPid\):	\(.*\)$/\2/p' /proc/$i/status 2> /dev/null`)
	if [[ $? != 0 ]]; then
	    break
	fi
	
	printf "%s%6d %s\n" "$c" "${v[0]}" "$(cat /proc/$i/cmdline | tr '\0' ' ')"

	i=${v[1]}
	if [[ $i = 0 ]]; then
	    break
	fi
    done
}

for x in "$@"; do
    if [[ "$x" =  "-O0" ]]; then
	O0=
	rep[${#rep[@]}]="$x"
    elif [[ "$x" =~ -O.* ]]; then
	:
    elif [[ "$x" = "-s" ]]; then
	pid_trace > /tmp/cc-s-$$.log
    elif [[ "$x" = "-g3" ]]; then
	g3=
	rep[${#rep[@]}]="$x"
    elif [[ "$x" = "-D__OPTIMIZE__" ]]; then
	D=
	rep[${#rep[@]}]="$x"
    else
	rep[${#rep[@]}]="$x"
    fi
done

${CC} ${O0} ${g3} "${rep[@]}" ${D} 
