#!/bin/bash

function print_usage
{
    echo "$0 DIST SRPM [OUTPUT]"	
}

function pid_trace
{
    local i
    local v=

    i=$$
    while true; do
	v=(`sed -n -e 's/^\(Pid\|PPid\):	\(.*\)$/\2/p' /proc/$i/status 2> /dev/null`)
	if [[ $? != 0 ]]; then
	    break
	fi
	
	printf "%s%6d %s\n" "$c" "${v[0]}" "$(cat /proc/$i/cmdline | tr '\0' ' ')"

	i=${v[1]}
	if [[ $i = 0 ]]; then
	    break
	fi
    done
}

function main
{
    local dist=$1
    local srpm=$2
    local output=${3:-/srv/debugs}


    if ! [ -f /etc/mock/${dist}.cfg ]; then
	echo "No such dist: ${dist}" 1>&2
	print_usage 1>&2
	return 1
    fi
    
    if [ -z "${srpm}" ]; then
	print_usage 1>&2
	return 1
    fi

    if ! [ -f $srpm ]; then
	echo "Cannot find $srpm" 1>&2
	return 1
    fi

    if ! mkdir -p $output; then
	return 1
    fi

    local pkg_name=$(rpm --nosignature -qp --queryformat="%{NAME}\n" $srpm )
    local pkg_char=${pkg_name:0:1}
    local pkg_version=$(rpm --nosignature -qp --queryformat="%{VERSION}\n" $srpm )
    local pkg_release=$(rpm --nosignature -qp --queryformat="%{RELEASE}\n" $srpm )

    local pkg_dir=/sources/${pkg_char}/${pkg_name}/${pkg_version}-${pkg_release}
    local pkg_prebuild_dir=${pkg_dir}/pre-build

    O0g3_dir=$output${pkg_dir}/plugins/O0g3
    O0g3_status_file=${O0g3_dir}/STATUS
    O0g3_version_file=${O0g3_dir}/VERSION

    local status=
    if [ -e "${O0g3_status_file}" ] && [ "${O0g3_status_file}" -nt "${srpm}" ]; then
	status=$(cat "${O0g3_status_file}")
	return $status
    fi

    if ! mkdir -p ${O0g3_dir}; then
	return 1
    fi

    mock \
	--root ${dist} \
	--clean
    mock \
	--no-cleanup-after      \
	--resultdir=${O0g3_dir} \
	--enable-plugin=O0g3    \
	--root ${dist}          \
	--rebuild ${srpm}       
    status=$?

    cd ${O0g3_dir}
    rm -f *.src.rpm
    mkdir -p root
    echo $status > "${O0g3_status_file}"
    rpm -q --qf "%{VERSION}-%{RELEASE}\n" mock-o0g3-plugin > "${O0g3_version_file}"

    local p
    if [ $status = 0 ]; then
	pid_trace > ${O0g3_dir}/LOCK
	for p in *.rpm; do
	    rpm2cpio $p 2>/dev/null | (cd root; cpio -dim 2>/dev/null)
	done
	find root -type f | while read f; do
	    if ! ( file $f | grep ELF > /dev/null 2>&1 ); then
		rm $f
	    fi
	done
	find root -type d -empty -delete

	rm ${O0g3_dir}/LOCK
	return 0
    else
	return 1
    fi
}

main "$@"
exit $?

# find root -type f | while read f; do
#     echo -n $f.es...
#     gosh ~/var/droite/es-src-objdump-dcall/driver.scm $f > ${f}.es
#     echo $?
#     echo -n $f.dot...
#     ${es2dot} sources ${pkg_name} ${pkg_version}-${pkg_release} ${pkg_prefixd} < ${f}.es > ${f}.dot
#     echo $?
#     echo -n $f.svg...
#     neato -Gstart=0 -Gsplines=true -Nfontsize=26 -Nfontsize=30  -Elen=15 -Tsvg ${f}.dot > ${f}.svg
#     echo $?
# done
